# yaml-language-server: $schema=https://docs.mergify.com/mergify-configuration-schema.json

queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label~=merge-queue|dependencies|automated
    merge_conditions:
      - check-success=buildbot/nix-build
    merge_method: rebase

pull_request_rules:
  - name: automatic merge for documentation PRs
    conditions:
      - base=main
      - label=documentation
      - label=automated
      - check-success=buildbot/nix-build
    actions:
      merge:
        method: rebase

  - name: merge dependency updates using the merge queue
    conditions:
      - base=main
      - label=dependencies
      - label=automated
    actions:
      queue:
        name: default

  - name: merge using the merge queue
    conditions:
      - base=main
      - label=merge-queue
    actions:
      queue:
        name: default
