site_name: Ethereum.nix
site_description: Nix packages and NixOS modules for the Ethereum ecosystem
site_url: https://nix-community.github.io/ethereum.nix

repo_url: https://github.com/nix-community/ethereum.nix
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    # Palette toggle for dark mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for light mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - stylesheets/neoteroi-mkdocs.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - neoteroi.spantable
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - footnotes

nav:
  - Home: index.md
  - getting-started.md
  - apps.md
  - NixOS:
      - nixos/installation.md
      - Services:
          - nixos/running-geth.md
          - nixos/running-prysm-beacon.md
          - nixos/running-lighthouse-beacon.md
          - nixos/running-nimbus-beacon.md
          - nixos/backup-and-restore.md
      - Module Options:
          - nixos/modules/erigon.md
          - nixos/modules/geth-bootnode.md
          - nixos/modules/geth.md
          - nixos/modules/mev-boost.md
          - nixos/modules/nethermind.md
          - nixos/modules/prysm-beacon.md
          - nixos/modules/prysm-validator.md
          - nixos/modules/lighthouse-beacon.md
          - nixos/modules/lighthouse-validator.md
          - nixos/modules/nimbus-beacon.md
  - Contributing:
      - Reporting a bug: contributing/reporting-a-bug.md
      - Reporting a docs issue: contributing/reporting-a-docs-issue.md
      - Requesting a change: contributing/reporting-a-change.md
      - Asking a question: https://github.com/nix-community/ethereum.nix/discussions
  - Other:
      - license.md

extra:
  homepage: https://nix-community.github.io/ethereum.nix
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nix-community/ethereum.nix
      name: Ethereum.nix on Github
  generator: false # hide the line "Made with Material for MkDocs"

copyright: Copyright &copy; 2022-2025 Ethereum.nix contributors
