name: Request a change
description: Want to submit an idea? Propose a change or feature request
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: >-
        This field is optional. You may provide additional context for the idea
        you want to propose, helping us to understand what you are working on
        and what you are trying to achieve. If the context is not relevant, you
        can leave this field empty.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please provide a detailed description of your idea in 2-3 sentences so
        that we maintainers can fully understand what change, feature, or the
        improvement you are proposing. Don't yet explain the benefits of your
        idea, we'll come to that. Focus on functionality.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description:
        Please ensure your idea fulfills all of the following requirements. If
        you need clarification on a specific requirement, follow the link to
        learn about it and understand why it is necessary before ticking the box.
        This will save the maintainers and you valuable time.
      options:
        - label: >-
            I have verified that my idea is a change request and not a bug report
          required: true
