# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.
{fetchNuGet}: [
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI";
    version = "9.0.0";
    hash = "sha256-RHu0pdkSGPvaKtAecbT0VpVPgS8v7f6n86sF8bLjgb8=";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI.Client";
    version = "9.0.0";
    hash = "sha256-ghXhPV6oGCxVogZMW+dnzsHkl8fKxWHcdLdiS6xmdqM=";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI.Core";
    version = "9.0.0";
    hash = "sha256-FEa3Lv6dfX/ADomevS8peHrmSWiPa5yl5IsiP2iXBgM=";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI.Data";
    version = "9.0.0";
    hash = "sha256-C7wwtuImGGbtCOlvKOrEJK56X/6rjrOQFC85PZkcdYI=";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI.InMemory.Storage";
    version = "9.0.0";
    hash = "sha256-y4WpGFdeBL9lE3WDado38MYaZokWdvdtmGZtKlgPcJ8=";
  })
  (fetchNuGet {
    pname = "Autofac";
    version = "8.1.0";
    hash = "sha256-eDULsT32tESiX89CZTwvL061LwmPjjsxMvU8sYvJYE4=";
  })
  (fetchNuGet {
    pname = "Autofac";
    version = "8.4.0";
    hash = "sha256-IxU/qfyiAqbAOMT6Fh7jDOmsYz5Jj3nyUNXgIsAxDbk=";
  })
  (fetchNuGet {
    pname = "Autofac.Extensions.DependencyInjection";
    version = "10.0.0";
    hash = "sha256-ACQwFG8a5LMoqGyHI/YpwVyXZQYqM5+wnk0q2BbGVZ4=";
  })
  (fetchNuGet {
    pname = "BinaryEncoding";
    version = "1.4.0";
    hash = "sha256-AP06LKHMY98FDSLSjxsc9oUzpbeQzcSTZl1DrVzVFxU=";
  })
  (fetchNuGet {
    pname = "BouncyCastle.Cryptography";
    version = "2.4.0";
    hash = "sha256-DoDZNWtYM+0OLIclOEZ+tjcGXymGlXvdvq2ZMPmiAJA=";
  })
  (fetchNuGet {
    pname = "BouncyCastle.Cryptography";
    version = "2.6.2";
    hash = "sha256-Yjk2+x/RcVeccGOQOQcRKCiYzyx1mlFnhS5auCII+Ms=";
  })
  (fetchNuGet {
    pname = "Ckzg.Bindings";
    version = "2.1.1.1463";
    hash = "sha256-z9cAgo9x4thOGGZXPlHphDRgAXLGC0q9tSiGfs33/rY=";
  })
  (fetchNuGet {
    pname = "Common.Logging";
    version = "3.4.1";
    hash = "sha256-1xeblzYhQCKveUv6z8Z17Dp1P6KKdR8xGykl7tpqbQc=";
  })
  (fetchNuGet {
    pname = "Common.Logging.Core";
    version = "3.4.1";
    hash = "sha256-XhZ4hnefxjEcQm6Ls/OFPZCDONFs6j/tM9CKQA8DCBo=";
  })
  (fetchNuGet {
    pname = "CommunityToolkit.HighPerformance";
    version = "8.4.0";
    hash = "sha256-q9RZZvLlvk1sXuIr5wdBxyTf9o0G2mk23xtNGDf6vGs=";
  })
  (fetchNuGet {
    pname = "ConcurrentHashSet";
    version = "1.3.0";
    hash = "sha256-5j64jgwDsB7jzshYm61orG7dHh7UDVGBsfyG/a9rXhI=";
  })
  (fetchNuGet {
    pname = "Crc32.NET";
    version = "1.2.0";
    hash = "sha256-sMQNIppJXHU2mULn5b//uRbbPMyguH9QlG6HKVIYUmE=";
  })
  (fetchNuGet {
    pname = "DnsClient";
    version = "1.8.0";
    hash = "sha256-Xc8BOCI9M8gSM5raVnPezA4yeO1eoyxXPPn9jh5/RaY=";
  })
  (fetchNuGet {
    pname = "FastEnum";
    version = "2.0.5";
    hash = "sha256-/kqeGR8glV4k1/XocQOoy08l+6tS05Lq26iJ8JtKsXE=";
  })
  (fetchNuGet {
    pname = "FastEnum.Core";
    version = "2.0.5";
    hash = "sha256-xGrTK7b5OmcZftXE1AEkaZtKIMhY9ZijjjFe+dTnDFg=";
  })
  (fetchNuGet {
    pname = "FastEnum.Generators";
    version = "2.0.5";
    hash = "sha256-/WhVSZ8t+gwD87FUAY3huLsN9NGFpC3TRTwdAYxHfLE=";
  })
  (fetchNuGet {
    pname = "Fractions";
    version = "7.3.0";
    hash = "sha256-wr4I1mj1qrXjD2Z3dca70OBe14zZNGagDLW9/8xQtCU=";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "6.0.2";
    hash = "sha256-JV4aCTlEgzWndr6H2Fr1XzVmh+/fSW6VWWjwbWIYn2A=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.28.3";
    hash = "sha256-jiA/FeYEEk/u9O1gtdnOzatym+/uHyaRJSdp34TOb1o=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.31.1";
    hash = "sha256-UEcn4H8F+zK0AjSmz1aTyyMksLxJOGNf2IROtF+DydA=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf.Tools";
    version = "3.31.1";
    hash = "sha256-zB+Jg0DGeqhY56b4BO3EG6sqoy1pY2gZlukW/LlGcb0=";
  })
  (fetchNuGet {
    pname = "Grpc";
    version = "2.46.6";
    hash = "sha256-UvshzRfdXji+35rPAlS5Kcc5On6OxvFJ0Lbhk+CRQv4=";
  })
  (fetchNuGet {
    pname = "Grpc.Core";
    version = "2.46.6";
    hash = "sha256-/8HjIi72DMNH8WMCHcinEmNwdHWudZlc3s7K3hEV3tM=";
  })
  (fetchNuGet {
    pname = "Grpc.Core.Api";
    version = "2.46.6";
    hash = "sha256-HjqMERYygA3hrkPVJ489qMsANGXYxuh/23xbLeBAsLA=";
  })
  (fetchNuGet {
    pname = "Grpc.Tools";
    version = "2.72.0";
    hash = "sha256-IaN+NBnywsdjIfzc7OoJgkDc1SdWeGbpxHlHe4cSbes=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core";
    version = "2.14.1";
    hash = "sha256-EXvojddPu+9JKgOG9NSQgUTfWq1RpOYw7adxDPKDJ6o=";
  })
  (fetchNuGet {
    pname = "IdentityModel";
    version = "5.2.0";
    hash = "sha256-rIpeZtSU3oe9burxx7EkaAH1kCsU2+sQLvvgoYWk2/o=";
  })
  (fetchNuGet {
    pname = "IdentityModel.OidcClient";
    version = "5.2.1";
    hash = "sha256-qX1V/pyikX6u6s930OOMKdoA9e2Iyq4Sqd2XBgcUp4A=";
  })
  (fetchNuGet {
    pname = "IPNetwork2";
    version = "2.1.2";
    hash = "sha256-E6pmGR1k7cETugh2EWRtdksnzlkdYf4s4BSWI2yoTjs=";
  })
  (fetchNuGet {
    pname = "Keccak256";
    version = "1.0.0";
    hash = "sha256-QloI81OzR7RIRDQKEJUu/Q8++sujl2Jq0/oxblwDYRA=";
  })
  (fetchNuGet {
    pname = "KubernetesClient";
    version = "15.0.1";
    hash = "sha256-nQUuXtP29TC2LmrGUwdwaYhouxb0TQdHN04+0bz5A1Q=";
  })
  (fetchNuGet {
    pname = "libsodium";
    version = "1.0.16";
    hash = "sha256-hSrMyXlZJXq79LcvYqO1pl96eDxJqyj9Tzw23XjARq8=";
  })
  (fetchNuGet {
    pname = "libsodium";
    version = "1.0.20";
    hash = "sha256-BsitQQnUSm1YupzI5N/LFx0kPFdk1FP8VdM1S3uttvs=";
  })
  (fetchNuGet {
    pname = "Makaretu.Dns";
    version = "2.0.1";
    hash = "sha256-zeIKCov4J6rKfbgsre0hEDVoFyHVGsrRAf/izZqTytA=";
  })
  (fetchNuGet {
    pname = "Makaretu.Dns.Multicast";
    version = "0.27.0";
    hash = "sha256-B/9YIUNmmbjjyeqQdE2qWlr/KCaacFgZKrhvSwEER5Q=";
  })
  (fetchNuGet {
    pname = "MathNet.Numerics";
    version = "5.0.0";
    hash = "sha256-RHJCVM6OxquJF7n5Mbe/oNbucBbkge6ULcbAczOgmVo=";
  })
  (fetchNuGet {
    pname = "MathNet.Numerics.FSharp";
    version = "5.0.0";
    hash = "sha256-pPbh8JdmMjBgEu84c/qV4YJ+LLr4+c31C6t++u29qBs=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Cryptography.Internal";
    version = "9.0.8";
    hash = "sha256-tqsZDbzOTjYsY97Mn7+sU9/AqL8uAMPzFb/hWXtCcKA=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.DataProtection";
    version = "9.0.8";
    hash = "sha256-48FUoxAcBBEaHtbCiL96vs5TMKsthfL/26YPERf3/v4=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.DataProtection.Abstractions";
    version = "9.0.8";
    hash = "sha256-PofI54q+XrN7VpRQDoaDU3+U08DiObrgq01p0Rg1zEI=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.DataProtection.Extensions";
    version = "9.0.8";
    hash = "sha256-U8RygjgIbrTINnP3inUELvmwOtCFgX3G1ez9P2IvpRc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    hash = "sha256-49+H/iFwp+AfCICvWcqo9us4CzxApPKC37Q5Eqrw+JU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Tasks.Git";
    version = "8.0.0";
    hash = "sha256-vX6/kPij8vNAu8f7rrvHHhPrNph20IcufmrBgZNxpQA=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.Core";
    version = "7.5.0";
    hash = "sha256-QePcO+HHptFL2MNNvm9yNr6OlJUPHR5aoT9Glmof1IQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.V8";
    version = "7.5.0";
    hash = "sha256-SACYSAt6evj8nXcWvPcW6lsJpx0YdaG5gSs4kSyvM9M=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.V8.ICUData";
    version = "7.5.0";
    hash = "sha256-hB35+sXWRiLxbp3aymIbR2nDvCL9CJ3ih4xQ0bnDtxw=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.V8.Native.linux-arm64";
    version = "7.5.0";
    hash = "sha256-Q6fMMJjBGDnE3N32hxlYH8fDvoo8xEckExl1gLG4HB8=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.V8.Native.linux-x64";
    version = "7.5.0";
    hash = "sha256-zvn1eQpw+6htjXGfFxS7DGLR3aJudUFfZI6kZEVhms4=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.V8.Native.osx-arm64";
    version = "7.5.0";
    hash = "sha256-HYm51F7JzTJ1JrLfh+qlof3IC/LhUP38PKlA7Nqvi+M=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.V8.Native.osx-x64";
    version = "7.5.0";
    hash = "sha256-ROIfKUUqbyEREOTiU8GeSEEI+IYMN64boZN3QxpijZY=";
  })
  (fetchNuGet {
    pname = "Microsoft.ClearScript.V8.Native.win-x64";
    version = "7.5.0";
    hash = "sha256-+iCUkEHRIJMdgEQauqob1BC+H0bcb7Pln9yYBUHc7SI=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.3.3";
    hash = "sha256-pkZiggwLw8k+CVSXKTzsVGsT+K49LxXUS3VH5PNlpCY=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.5.0";
    hash = "sha256-qo1oVNTB9JIMEPoiIZ+02qvF/O8PshQ/5gTjsY9iX0I=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.5.0";
    hash = "sha256-5dZTS9PYtY83vyVa5bdNG3XKV5EjcnmddfUqWmIE29A=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp.Workspaces";
    version = "4.5.0";
    hash = "sha256-Kmyt1Xfcs0rSZHvN9PH94CKAooqMS9abZQY7EpEqb2o=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Workspaces.Common";
    version = "4.5.0";
    hash = "sha256-WM7AXJYHagaPx2waj2E32gG0qXq6Kx4Zhiq7Ym3WXPI=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.0.1";
    hash = "sha256-0huoqR2CJ3Z9Q2peaKD09TV3E6saYSqDGZ290K8CrH8=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore";
    version = "8.0.0";
    hash = "sha256-Z6dlgOQrYcSCcRaXPNnYLC87sg4OGRS+p4Tv3EFXFfY=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore";
    version = "8.0.11";
    hash = "sha256-uvcAmj7ob2X/JKLleNwanpNs0X3PkJl3je6ZsHeWooE=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Abstractions";
    version = "8.0.0";
    hash = "sha256-QxPc73WzjE63Pzuxc/xr/uQc0C+v6xVd2N0iIUJKOQU=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Abstractions";
    version = "8.0.11";
    hash = "sha256-qKe+WBIlyZ1CS2H9JGWsYiWxkUzGjwIHtx/q3FPCDr8=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Analyzers";
    version = "8.0.0";
    hash = "sha256-SidpTl9AveYiXHa+TtvyHnRTOn02lmab4qXPf0FTi+0=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Analyzers";
    version = "8.0.11";
    hash = "sha256-eKhcGqCN34F2i7/FeKSq1gyMjNq3ikq+UpE/1SbXecY=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Design";
    version = "8.0.11";
    hash = "sha256-in7Ppl/tEEM/2r+l+uuSjWLXk7fHbJRVmLzskYfAhMQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.InMemory";
    version = "8.0.11";
    hash = "sha256-ur4S18FWg9gdVSV+VYT6vDo5yeev++BAwIYSJhFRls0=";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Relational";
    version = "8.0.11";
    hash = "sha256-st6V0S7j+FyK7r9X6uObpuhSoac/z5QOF1DUPnhffgE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Caching.Abstractions";
    version = "8.0.0";
    hash = "sha256-xGpKrywQvU1Wm/WolYIxgHYEFfgkNGeJ+GGc5DT3phI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Caching.Memory";
    version = "8.0.0";
    hash = "sha256-RUQe2VgOATM9JkZ/wGm9mreKoCmOS4pPyvyJWBqMaC8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Caching.Memory";
    version = "8.0.1";
    hash = "sha256-5Q0vzHo3ZvGs4nPBc/XlBF4wAwYO8pxq6EGdYjjXZps=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "3.1.0";
    hash = "sha256-KI1WXvnF/Xe9cKTdDjzm0vd5h9bmM+3KinuWlsF/X+c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "8.0.0";
    hash = "sha256-9BPsASlxrV8ilmMCjdb3TiUcm5vFZxkBnAI/fNBSEyA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "9.0.0";
    hash = "sha256-uBLeb4z60y8z7NelHs9uT3cLD6wODkdwyfJm6/YZLDM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "3.1.0";
    hash = "sha256-GMxvf0iAiWUWo0awlDczzcxNo8+MITBLp0/SqqYo8Lg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "8.0.0";
    hash = "sha256-4eBpDkf7MJozTZnOwQvwcfgRKQGcNXe0K/kF+h5Rl8o=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "9.0.0";
    hash = "sha256-xtG2USC9Qm0f2Nn6jkcklpyEDT3hcEZOxOwTc0ep7uc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "9.0.8";
    hash = "sha256-hes+QZM3DQ1R/8CDOdWObk6s1oGhzFqka8Qc7Baf9PY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "3.1.0";
    hash = "sha256-/B7WjPZPvRM+CPgfaCQunSi2mpclH4orrFxHGLs8Uo4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.0";
    hash = "sha256-GanfInGzzoN2bKeNwON8/Hnamr6l7RTpYLA49CNXD9Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "9.0.0";
    hash = "sha256-6ajYWcNOQX2WqftgnoUmVtyvC1kkPOtTCif4AiKEffU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "3.1.0";
    hash = "sha256-S72hzDAYWzrfCH5JLJBRtwPEM/Xjh17HwcKuA3wLhvU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "5.0.0";
    hash = "sha256-RN478YJQE0YM0g+JztXp00w57CIF4bb48hSD/z3jTZc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.0";
    hash = "sha256-+qIDR8hRzreCHNEDtUcPfVHQdurzWPo/mqviCH78+EQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.1";
    hash = "sha256-O9g0jWS+jfGoT3yqKwZYJGL+jGSIeSbwmvomKDC3hTU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "9.0.0";
    hash = "sha256-dAH52PPlTLn7X+1aI/7npdrDzMEFPMXRv4isV1a+14k=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "9.0.8";
    hash = "sha256-fJOwbtlmP6mXGYqHRCqtb7e08h5mFza6Wmd1NbNq3ug=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "3.1.0";
    hash = "sha256-cG0XS3ibJ9siu8eaQGJnyRwlEbQ9c/eGCtvPjs7Rdd8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "5.0.0";
    hash = "sha256-0sfuxZ07HsMZJpKatDrW6I671uJBYWsUgAyoDZA2n50=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.0";
    hash = "sha256-75KzEGWjbRELczJpCiJub+ltNUMMbz5A/1KQU+5dgP8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.1";
    hash = "sha256-lzTYLpRDAi3wW9uRrkTNJtMmaYdtGJJHdBLbUKu60PM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.2";
    hash = "sha256-UfLfEQAkXxDaVPC7foE/J3FVEXd31Pu6uQIhTic3JgY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "9.0.0";
    hash = "sha256-CncVwkKZ5CsIG2O0+OM9qXuYXh3p6UGyueTHSLDVL+c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "9.0.8";
    hash = "sha256-uFBeyx8WTgDX2z8paf6ZAQ45WexaWG8uzO5x+qGrPRU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "8.0.2";
    hash = "sha256-PyuO/MyCR9JtYqpA1l/nXGh+WLKCq34QuAXN9qNza9Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics";
    version = "8.0.0";
    hash = "sha256-fBLlb9xAfTgZb1cpBxFs/9eA+BlBvF8Xg0DMkBqdHD4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "8.0.0";
    hash = "sha256-USD5uZOaahMqi6u7owNWx/LR4EDrOwqPrAAim7iRpJY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "8.0.1";
    hash = "sha256-d5DVXhA8qJFY9YbhZjsTqs5w5kDuxF5v+GD/WZR1QL0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "9.0.8";
    hash = "sha256-nsgRtkUUC5q+Wc76lu3xxRgOT0dw+EXGa4pFCeI0iEo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.HealthChecks";
    version = "8.0.11";
    hash = "sha256-wS+5kN0lREre+gv7//VuVb9oVkEzWHxKGiZJukj4Z30=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions";
    version = "8.0.11";
    hash = "sha256-JjWYaK5c+w8GUkNudYQKf2m3NwOQLYEeSFwL8kgTWC0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "8.0.0";
    hash = "sha256-uQSXmt47X2HGoVniavjLICbPtD2ReQOYQMgy3l0xuMU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "9.0.8";
    hash = "sha256-9X3roHvoAFzlTwVSlkbksB9EosKjVHeXuR5Jm682Wvk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "8.0.1";
    hash = "sha256-/bIVL9uvBQhV/KQmjA1ZjR74sMfaAlBb15sVXsGDEVA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "9.0.8";
    hash = "sha256-N1XwGfMh2a9grBfObp9md7YPSm7rlNZO5NG8OmHn8W4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Http";
    version = "3.1.0";
    hash = "sha256-nhkt3qVsTXccgrW3mvx8veaJICREzeJrXfrjXI7rNwo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Http";
    version = "8.0.0";
    hash = "sha256-UgljypOLld1lL7k7h1noazNzvyEHIJw+r+6uGzucFSY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "3.1.0";
    hash = "sha256-BDrsqgiLYAphIOlnEuXy6iLoED/ykFO53merHCSGfrQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "5.0.0";
    hash = "sha256-IyJiQk0xhESWjr231L7MsbFvFbphP6T8VwlKgVGgQeE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "6.0.0";
    hash = "sha256-8WsZKRGfXW5MsXkMmNVf6slrkw+cR005czkOP2KUqTk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "8.0.0";
    hash = "sha256-Meh0Z0X7KyOEG4l0RWBcuHHihcABcvCyfUXgasmQ91o=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "8.0.1";
    hash = "sha256-vkfVw4tQEg86Xg18v6QO0Qb4Ysz0Njx57d1XcNuj6IU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "9.0.0";
    hash = "sha256-kR16c+N8nQrWeYLajqnXPg7RiXjZMSFLnKLEs4VfjcM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "3.1.0";
    hash = "sha256-D3GHIGN0r6zLHHP2/5jt6hB0oMvRyl5ysvVrPVmmyv8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "5.0.0";
    hash = "sha256-jJtcchUS8Spt/GddcDtWa4lN1RAVQ2sxDnu1cgwa6vs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.0";
    hash = "sha256-Jmddjeg8U5S+iBTwRlVAVLeIHxc4yrrNgqVMOB7EjM4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.2";
    hash = "sha256-cHpe8X2BgYa5DzulZfq24rg8O2K5Lmq2OiLhoyAVgJc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "9.0.0";
    hash = "sha256-iBTs9twjWXFeERt4CErkIIcoJZU1jrd1RWCI8V5j7KU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "9.0.8";
    hash = "sha256-vaUApbwsqKt7+AItgusbCKKdTyOg/5KCdSZjDZarw20=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "8.0.0";
    hash = "sha256-mzmstNsVjKT0EtQcdAukGRifD30T82BMGYlSu8k4K7U=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "9.0.0";
    hash = "sha256-ysPjBq64p6JM4EmeVndryXnhLWHYYszzlVpPxRWkUkw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "8.0.0";
    hash = "sha256-bdb9YWWVn//AeySp7se87/tCN2E7e8Gx2GPMw28cd9c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "9.0.0";
    hash = "sha256-N2t9EUdlS6ippD4Z04qUUyBuQ4tKSR/8TpmKScb5zRw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ObjectPool";
    version = "7.0.0";
    hash = "sha256-JxlxPnjmWbEhYLNWlSn+kNxUfwvlxgKiKFjkJyYGn5Y=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ObjectPool";
    version = "9.0.8";
    hash = "sha256-nhzUsWbmnKS9mZXOlRk0O5iy2lJpYw7YW0JDJKQ37XU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "3.1.0";
    hash = "sha256-0EOsmu/oLAz9WXp1CtMlclzdvs5jea0zJmokeyFnbCo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "5.0.0";
    hash = "sha256-Xq2JIa2Rg9vnLnZ75k4ydyT4j2A+G6UUx6iDc959teU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.0";
    hash = "sha256-n2m4JSegQKUTlOsKLZUUHHKMq926eJ0w9N9G+I3FoFw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.2";
    hash = "sha256-AjcldddddtN/9aH9pg7ClEZycWtFHLi9IPe1GGhNQys=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "9.0.0";
    hash = "sha256-DT5euAQY/ItB5LPI8WIp6Dnd0lSvBRP35vFkOXC68ck=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "9.0.8";
    hash = "sha256-AbwIL8sSZ/qDBKbvabHp1tbExBFr73fYjuXJiV6On1U=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "8.0.0";
    hash = "sha256-A5Bbzw1kiNkgirk5x8kyxwg9lLTcSngojeD+ocpG1RI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "9.0.0";
    hash = "sha256-r1Z3sEVSIjeH2UKj+KMj86har68g/zybSqoSjESBcoA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "3.1.0";
    hash = "sha256-K/cDq+LMfK4cBCvKWkmWAC+IB6pEWolR1J5zL60QPvA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "5.0.0";
    hash = "sha256-pj1BdHlmYm5HZifp/yB3lwDkdw0/jcIF0vYg6O1kmGs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    hash = "sha256-FU8qj3DR8bDdc1c+WeGZx/PCZeqqndweZM9epcpXjSo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "9.0.0";
    hash = "sha256-ZNLusK1CRuq5BZYZMDqaz04PIKScE2Z7sS2tehU7EJs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "9.0.8";
    hash = "sha256-K3T8krgXZmvQg87AQQrn9kiH2sDyKzRUMDyuB/ItmPc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Identity.Abstractions";
    version = "9.3.0";
    hash = "sha256-vzR37PdbKQaCveLin2/o+nwgGl9EY2ISB36y+t7k1Qc=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Abstractions";
    version = "7.1.2";
    hash = "sha256-QN2btwsc8XnOp8RxwSY4ntzpqFIrWRZg6ZZEGBZ6TQY=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Abstractions";
    version = "8.13.1";
    hash = "sha256-zDoi55HDQG0Xr1W0PLbmBXGccRaSMI4afT/73J4GRuo=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "7.1.2";
    hash = "sha256-kVTS9i3khR7/0JBk52jzv4FUmBsbqntqVyqkDA/APvk=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "8.13.1";
    hash = "sha256-V8w1vp4BU54GUCn1MeMzbk1erJOhRkaGvfT36CQoQMg=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "7.1.2";
    hash = "sha256-6M7Y1u2cBVsO/dP+qrgkMLisXbZgMgyWoRs5Uq/QJ/o=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "8.13.1";
    hash = "sha256-Y/djq0pR3iKykXY8TALZnJaU8PhWDcEweCNUWz99QQk=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "7.1.2";
    hash = "sha256-qf8y8KCo1ysrK+jCrnR+ARHwlfMWPXLxe7a41FVg4OA=";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "8.13.1";
    hash = "sha256-+bXBDOsA5qxYRbyIHLCt6h/Zs0y/k/KA4Yyof5q9g7k=";
  })
  (fetchNuGet {
    pname = "Microsoft.IO.RecyclableMemoryStream";
    version = "3.0.0";
    hash = "sha256-WBXkqxC5g4tJ481sa1uft39LqA/5hx5yOfiTfMRMg/4=";
  })
  (fetchNuGet {
    pname = "Microsoft.IO.RecyclableMemoryStream";
    version = "3.0.1";
    hash = "sha256-unFg/5EcU/XKJbob4GtQC43Ydgi5VjeBGs7hfhj4EYo=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.0.1";
    hash = "sha256-mZotlGZqtrqDSoBrZhsxFe6fuOv5/BIo0w2Z2x0zVAU=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.1";
    hash = "sha256-8hLiUKvy/YirCWlFwzdejD2Db3DaXhHxT7GSZx/znJg=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    hash = "sha256-LIcg1StDcQLPOABp4JRXIs837d7z0ia6+++3SF3jl1c=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.0.1";
    hash = "sha256-lxxw/Gy32xHi0fLgFWNj4YTFBSBkjx5l6ucmbTyf7V4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.3";
    hash = "sha256-WLsf1NuUfRWyr7C7Rl9jiua9jximnVvzy6nk2D2bVRc=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Azure.Containers.Tools.Targets";
    version = "1.22.1";
    hash = "sha256-hvatFk/UgSU+s//1+YPYYLMMby0Y4FCTs2k8fqMMgoU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-mBNDmPXNTW54XLnPAUwBRvkIORFM7/j0D0I2SyQPDEg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    hash = "sha256-9kylPGfKZc58yFqNKa77stomcoNnMeERXozWJzDcUIA=";
  })
  (fetchNuGet {
    pname = "Mono.TextTemplating";
    version = "2.2.1";
    hash = "sha256-4TYsfc8q74P8FuDwkIWPO+VYY0mh4Hs4ZL8v0lMaBsY=";
  })
  (fetchNuGet {
    pname = "Multiformats.Base";
    version = "2.0.1";
    hash = "sha256-DJWKq2kllwCuu8qCZ+qUriyn0955XGGNsYL0+lX8Mzg=";
  })
  (fetchNuGet {
    pname = "Multiformats.Base";
    version = "2.0.2";
    hash = "sha256-iC4N5IFJWH5ctjknowleq+AsQLaWMOwcwXfHhwwY8Xw=";
  })
  (fetchNuGet {
    pname = "Multiformats.Hash";
    version = "1.5.0";
    hash = "sha256-Muq09iF6q755Qr1d5x+aDT38aLBQy116XfHpE94/29E=";
  })
  (fetchNuGet {
    pname = "murmurhash";
    version = "1.0.2";
    hash = "sha256-UHhb+MqCORaCHt/hFDS6FR662qwytmMeeNxVq5clkX4=";
  })
  (fetchNuGet {
    pname = "NBitcoin.Secp256k1";
    version = "3.1.5";
    hash = "sha256-iT6+8Ohm0hGy3DlSBlhyhOGjc6EdGlAz1bC1QcafPr8=";
  })
  (fetchNuGet {
    pname = "Nethermind.Crypto.Bls";
    version = "1.0.5";
    hash = "sha256-EI8JsiEKw+laRhA3n+PFivJtAcyfGZJ+dIuBlqpdiKw=";
  })
  (fetchNuGet {
    pname = "Nethermind.Crypto.SecP256k1";
    version = "1.5.0";
    hash = "sha256-VztufDcdrk0u6k4MJI9yruieCnXg+Xi4wtaqokh/mPc=";
  })
  (fetchNuGet {
    pname = "Nethermind.Crypto.SecP256r1";
    version = "1.0.0-preview.6";
    hash = "sha256-IrsC/YdPP375pUroSty4kZiPDAWP4w+GyXGnN5y+dPo=";
  })
  (fetchNuGet {
    pname = "Nethermind.DotNetty.Buffers";
    version = "1.0.2.76";
    hash = "sha256-GgmB9EHhpeZjEIL9u+PgSHVL2vR8ywTFR028smOyGpo=";
  })
  (fetchNuGet {
    pname = "Nethermind.DotNetty.Codecs";
    version = "1.0.2.76";
    hash = "sha256-AQj8WtmhanxnByD2D5iqxZmAyYnoXckruY8ZDlCTIes=";
  })
  (fetchNuGet {
    pname = "Nethermind.DotNetty.Common";
    version = "1.0.2.76";
    hash = "sha256-D0+9hOx6o183XkBItp8sIA7DFgkIVDFkJjEjTFrl9XU=";
  })
  (fetchNuGet {
    pname = "Nethermind.DotNetty.Handlers";
    version = "1.0.2.76";
    hash = "sha256-HBbLE1QdLPEWQf2CKcK9EPmM2XUxWjfyB0Xq3JDOt8M=";
  })
  (fetchNuGet {
    pname = "Nethermind.DotNetty.Transport";
    version = "1.0.2.76";
    hash = "sha256-b77Kybf2O1NvNmXQnauDMzBjXER4jouJN7eA2dmIlV4=";
  })
  (fetchNuGet {
    pname = "Nethermind.GmpBindings";
    version = "1.0.3";
    hash = "sha256-qYE1TkmlbItCszf7XTjvt4mVQncXjoXUBOD7J+nTu5U=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p";
    version = "1.0.0-preview.45";
    hash = "sha256-ETKIUxe997nVFkSZHsSMkrHiZbCvbSl5FW7tiqzi5xI=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Core";
    version = "1.0.0-preview.45";
    hash = "sha256-5uKZYw1VR6N5mjW7RDIlPOafbterT6Oir0dIF9AK0L0=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Identify";
    version = "1.0.0-preview.45";
    hash = "sha256-k7kaOPk05Db1u9c52yWE4Vhf0EmCGpqwPL5Pzm+2WHI=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.IpTcp";
    version = "1.0.0-preview.45";
    hash = "sha256-dOVz/LFf/ePR0cXuLgK6AvGx9m1tmDBxq5mPNqyRXcM=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.MDns";
    version = "1.0.0-preview.45";
    hash = "sha256-QTiV0Yir3EerplaceCIF4P/0HsO8BmDbHg9qtHXeW3w=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Multistream";
    version = "1.0.0-preview.45";
    hash = "sha256-nS9OEy6ImDTggZ3QJytHJCWDCL6ne9uECPHaHuWtKww=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Noise";
    version = "1.0.0-preview.45";
    hash = "sha256-dl3uTW6Ys0NYA3hrFM/nFMCq7rbwZ8Ydpu3O4ugq3xo=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Ping";
    version = "1.0.0-preview.45";
    hash = "sha256-dZutocjTFrhv60MyM++Y2vVdauW50c1Y81yGcdeTKpo=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Plaintext";
    version = "1.0.0-preview.45";
    hash = "sha256-JVV2y+/uXNcz4I9UZXk2fgFCYjATY1VKcJ7n0Qaf4CA=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Pubsub";
    version = "1.0.0-preview.45";
    hash = "sha256-8yKkahFDc5yF2kEU5zgQPcNy9bBPrRA6P//MWLntIWQ=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.PubsubPeerDiscovery";
    version = "1.0.0-preview.45";
    hash = "sha256-KBwbEqWs1q/ufPajLBmtANRuO3Ym9KYLVS96twtNZdY=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Quic";
    version = "1.0.0-preview.45";
    hash = "sha256-Fq0un8GtxwzBCcwmQOW5OgV2d/gqBLN69cBZiEpsIfU=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Relay";
    version = "1.0.0-preview.45";
    hash = "sha256-xQ50dhaR73g4LUTHMqmqqVJ2s8hlKN7YzUqLYUg0VoI=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Tls";
    version = "1.0.0-preview.45";
    hash = "sha256-tfEezIuoZti/cKKjzfQv1BJSEH1YLGrq1iKYyTxZnrI=";
  })
  (fetchNuGet {
    pname = "Nethermind.Libp2p.Protocols.Yamux";
    version = "1.0.0-preview.45";
    hash = "sha256-ok4NIzDRGWr9qyNzkoV9bgRdB6mtD37+nHMuzBlWVP4=";
  })
  (fetchNuGet {
    pname = "Nethermind.MclBindings";
    version = "1.0.3-preview.1";
    hash = "sha256-l+6rO24PGJ3PhtqIN35fFyM+pJmpvnBCFMVMwQFSXLk=";
  })
  (fetchNuGet {
    pname = "Nethermind.Multiformats.Address";
    version = "1.1.8";
    hash = "sha256-iSWw9QZibjO71FfyVtsn7I5g9j7Z8gOExC+3yJwlEJk=";
  })
  (fetchNuGet {
    pname = "Nethermind.Multiformats.Base";
    version = "2.0.3-preview.1";
    hash = "sha256-xgp/eIhxiB6zrql0/fz1DcpDjBDK6Q+ZiT88stPNyJk=";
  })
  (fetchNuGet {
    pname = "Nethermind.Multiformats.Hash";
    version = "1.5.2-preview.1";
    hash = "sha256-tWJyFG0shqo3Os1n3ojM+iNFCmrKjqt/mZihvLANUDs=";
  })
  (fetchNuGet {
    pname = "Nethermind.Numerics.Int256";
    version = "1.3.6";
    hash = "sha256-sGL90p3HuBRuXxIEOWNOlBR6WLfXlXXQU18Zuk/bEWs=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.1";
    hash = "sha256-iNan1ix7RtncGWC9AjAZ2sk70DoxOsmEOgQ10fXm4Pw=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.0";
    hash = "sha256-Pp7fRylai8JrE1O+9TGfIEJrAOmnWTJRLWE+qJBahK0=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "Nito.Collections.Deque";
    version = "1.2.1";
    hash = "sha256-ChbJEzfLZyNpx6UlQTPEIvRUYt3VOL7BFzFXxlVXNY8=";
  })
  (fetchNuGet {
    pname = "NLog";
    version = "5.2.5";
    hash = "sha256-QCYHzZ45Gf30NzJaVmGR8kKhIkfrVVjl+J+dliJe3gk=";
  })
  (fetchNuGet {
    pname = "NLog";
    version = "5.5.1";
    hash = "sha256-cLAAj2QWWhbfh4vgnE/fLq5Rpr3uTe4ufnVWTig0nEo=";
  })
  (fetchNuGet {
    pname = "NLog.Targets.Seq";
    version = "4.0.2";
    hash = "sha256-k32yj0NthNVHE+PepU7t6UfeRLsRt8wWt4q2/COwM9U=";
  })
  (fetchNuGet {
    pname = "Noise.NET";
    version = "1.0.0";
    hash = "sha256-SuoaJ8ozz1XwCGLSprSnghxhD8SisrVmQWo9JOV5RVI=";
  })
  (fetchNuGet {
    pname = "NonBlocking";
    version = "2.1.2";
    hash = "sha256-orioa8JnOStiukyKGIuR3RFqeupdeqsFZrAWqn5mm0U=";
  })
  (fetchNuGet {
    pname = "Open.NAT.Core";
    version = "2.1.0.5";
    hash = "sha256-LqG5L2APr11142fsZPQ3clk3tJfAYBMXi1rP0EM9zDg=";
  })
  (fetchNuGet {
    pname = "PierTwo.Lantern.Discv5.Enr";
    version = "1.0.0-preview.6";
    hash = "sha256-Ng7WsNQW4PUeYlJC5Yartvru/oZBcV3il8SsoKXsVEs=";
  })
  (fetchNuGet {
    pname = "PierTwo.Lantern.Discv5.Rlp";
    version = "1.0.0-preview.6";
    hash = "sha256-EWha4wPQY8jSVM/V5/P3Y4DdLzdKn1bnYIH8E9HuTo8=";
  })
  (fetchNuGet {
    pname = "PierTwo.Lantern.Discv5.WireProtocol";
    version = "1.0.0-preview.6";
    hash = "sha256-dJqnY87zn4Q3383vsyT11C7ptXM0bf1Wt5ihiKjeSaU=";
  })
  (fetchNuGet {
    pname = "Polly";
    version = "8.6.2";
    hash = "sha256-JWPe3Une30ljf2z4aeshNSjz2CfIQZWw3IHiPvFgy6E=";
  })
  (fetchNuGet {
    pname = "Polly.Core";
    version = "8.6.2";
    hash = "sha256-jX1i7tkQwaY74qgVarx6vLeLIg7zonQwisFvm6nWrHs=";
  })
  (fetchNuGet {
    pname = "Portable.BouncyCastle";
    version = "1.8.5";
    hash = "sha256-qzDf3ZR4JrB1KNgV1PQUihAXG7k/lWVwdMUxs+8d5iI=";
  })
  (fetchNuGet {
    pname = "prometheus-net";
    version = "8.2.1";
    hash = "sha256-NxHeXd4fwwc4MMsT6mrfX81czjHnq2GMStWTabZxMDw=";
  })
  (fetchNuGet {
    pname = "prometheus-net.AspNetCore";
    version = "8.2.1";
    hash = "sha256-dhrATENkD/1GfSPBkAd3GvyHvzR5q+c+k22UTp33z+c=";
  })
  (fetchNuGet {
    pname = "Pyroscope";
    version = "0.12.0";
    hash = "sha256-lUdud4QAImt63vReG0ujoxdpLoFST2e28mQgohksrcg=";
  })
  (fetchNuGet {
    pname = "RocksDB";
    version = "10.2.1.58549";
    hash = "sha256-PENCJO1/l1ElQbJe+JugINzxBqDEoFfBbB/dpzfsktQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    hash = "sha256-4PGZqyWhZ6/HCTF2KddDsbmTTjxs2oW79YfkberDZS8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-LXUPLX3DJxsU1Pd3UwjO1PO9NM2elNEDXeu2Mu/vNps=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-qeSqaUI80+lqw5MK4vMpmO0CZaqrmYktwp6L+vQAb0I=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-SrHqT9wrCBsxILWtaJgGKd6Odmxm8/Mh7Kh0CUkZVzA=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-Jy01KhtcCl2wjMpZWH+X3fhHcVn+SyllWFY8zWlz/6I=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-wyv00gdlqf8ckxEdV7E+Ql9hJIoPcmYEuyeWb5Oz3mM=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-zi+b4sCFrA9QBiSGDD7xPV27r3iHGlV99gpyVUjRmc4=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-gybQU6mPgaWV3rBG2dbH6tT3tBq8mgze3PROdsuWnX0=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-VsP72GVveWnGUvS/vjOQLv1U80H2K8nZ4fDAmI61Hm4=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-4yKGa/IrNCKuQ3zaDzILdNPD32bNdy6xr5gdJigyF5g=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-HmdJhhRsiVoOOCcUvAwdjpMRiyuSwdcgEv2j9hxi+Zc=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-pVFUKuPPIx0edQKjzRon3zKq8zhzHEzko/lc01V/jdw=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-ReoazscfbGH+R6s6jkg5sIEHWNEvjEoHtIsMbpc7+tI=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-l8S9gt6dk3qYG6HYonHtdlYtBKyPb29uQ6NDjmrt3V4=";
  })
  (fetchNuGet {
    pname = "SCrypt";
    version = "2.0.0.2";
    hash = "sha256-RqSXi+nw9xPkkLol0UeoKu0wpgIsrhHM1uwXsiNSOQ4=";
  })
  (fetchNuGet {
    pname = "SimpleBase";
    version = "1.3.1";
    hash = "sha256-FtRIcfLYXxUftEhq8kHgNNkahde6Fv2hPVGZNezCW1Y=";
  })
  (fetchNuGet {
    pname = "SimpleBase";
    version = "4.0.2";
    hash = "sha256-bk+G35Fqs4jJRYU9rTxbBUQIXatcrTykKf/v5YxTaH0=";
  })
  (fetchNuGet {
    pname = "Snappier";
    version = "1.2.0";
    hash = "sha256-0qzOn4fpZXl42K4eOBPnueBWGNECi2Rkd50mhn1BMds=";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.3.0";
    hash = "sha256-yg95LNQOwFlA1tWxXdQkVyJqT4AnoDc+ACmrNvzGiZg=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.4.0";
    hash = "sha256-KTxAhYawFG2V5VX1jw3pzx3IrQXRgn1TsvgjPgxAbqA=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.0";
    hash = "sha256-THw2znu+KibfJRfD7cE3nRYHsm7Fyn5pjOOZVonFjvs=";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "4.4.0";
    hash = "sha256-L1xyspJ8pDJNVPYKl+FMGf4Zwm0tlqtAyQCNW6pT6/0=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.0.11";
    hash = "sha256-puoFMkx4Z55C1XPxNw3np8nzNGjH+G24j43yTIsDRL0=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    hash = "sha256-afY7VUtD6w/5mYqrce8kQrvDIfS2GXDINDh73IjxJKc=";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.3.0";
    hash = "sha256-KMY5DfJnDeIsa13DpqvyN8NkReZEMAFnlmNglVoFIXI=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.5.0";
    hash = "sha256-BliqYlL9ntbMXo5d7NUrKXwYN+PqdyqDIS5bp4qVr7Q=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "6.0.0";
    hash = "sha256-DKEbpFqXCIEfqp9p3ezqadn5b/S1YTk32/EQK+tEScs=";
  })
  (fetchNuGet {
    pname = "System.CommandLine";
    version = "2.0.0-beta6.25358.103";
    hash = "sha256-bBd8zRElNoxv793V1bpRbc6etWvLq3I9AKR0/gmhmBY=";
  })
  (fetchNuGet {
    pname = "System.Composition";
    version = "1.2.0";
    hash = "sha256-HqqQt/STMfAFN1FAtmiwDIsxiQRS3RxipLmnrwX4KTs=";
  })
  (fetchNuGet {
    pname = "System.Composition";
    version = "6.0.0";
    hash = "sha256-H5TnnxOwihI0VyRuykbOWuKFSCWNN+MUEYyloa328Nw=";
  })
  (fetchNuGet {
    pname = "System.Composition.AttributedModel";
    version = "1.2.0";
    hash = "sha256-QP2MEHz5nRWOdJJLrOMYuoj1pu6edrvKxr7HhMhrwHg=";
  })
  (fetchNuGet {
    pname = "System.Composition.AttributedModel";
    version = "6.0.0";
    hash = "sha256-03DR8ecEHSKfgzwuTuxtsRW0Gb7aQtDS4LAYChZdGdc=";
  })
  (fetchNuGet {
    pname = "System.Composition.Convention";
    version = "1.2.0";
    hash = "sha256-SnU2yZ4eX1V5ImAplfEpeE3N6CAhmEbk2nsv38rb3Kc=";
  })
  (fetchNuGet {
    pname = "System.Composition.Convention";
    version = "6.0.0";
    hash = "sha256-a3DZS8CT2kV8dVpGxHKoP5wHVKsT+kiPJixckpYfdQo=";
  })
  (fetchNuGet {
    pname = "System.Composition.Hosting";
    version = "1.2.0";
    hash = "sha256-+Ft2GwIQomlWBij/24jLz5/FNKiUcyrEQdoj0FZHxNU=";
  })
  (fetchNuGet {
    pname = "System.Composition.Hosting";
    version = "6.0.0";
    hash = "sha256-fpoh6WBNmaHEHszwlBR/TNjd85lwesfM7ZkQhqYtLy4=";
  })
  (fetchNuGet {
    pname = "System.Composition.Runtime";
    version = "1.2.0";
    hash = "sha256-PzalBZ2GSbe2N+DMalPA/q6lLytCcRUcxKSJ3bYCV68=";
  })
  (fetchNuGet {
    pname = "System.Composition.Runtime";
    version = "6.0.0";
    hash = "sha256-nGZvg2xYhhazAjOjhWqltBue+hROKP0IOiFGP8yMBW8=";
  })
  (fetchNuGet {
    pname = "System.Composition.TypedParts";
    version = "1.2.0";
    hash = "sha256-JchMANzR3TwkuhtJxyEAD2l20ATpGrmFhUGNg1uGkaw=";
  })
  (fetchNuGet {
    pname = "System.Composition.TypedParts";
    version = "6.0.0";
    hash = "sha256-4uAETfmL1CvGjHajzWowsEmJgTKnuFC8u9lbYPzAN3k=";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "9.0.8";
    hash = "sha256-i9i8sf1yUj0c1C+Kukl0e3bBHGo1sdvayftw2FoYXtA=";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.3.0";
    hash = "sha256-Xh3PPBZr0pDbDaK8AEHbdGz7ePK6Yi1ZyRWI1JM6mbo=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.0.11";
    hash = "sha256-P+rSQJVoN6M56jQbs76kZ9G3mAWFdtF27P/RijN8sj4=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-fkA79SjPbSeiEcrbbUsb70u9B7wqbsdM9s1LnoKj0gM=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "8.0.0";
    hash = "sha256-+aODaDEQMqla5RYZeq0Lh66j+xkPYxykrVvSCmJQ+Vs=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "8.0.1";
    hash = "sha256-zmwHjcJgKcbkkwepH038QhcnsWMJcHys+PEbFGC0Jgo=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "9.0.8";
    hash = "sha256-u10dcgug0Pwp83YNagVto8Pu3ieuByflYLNwAdX9Fm0=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-gVOv1SK6Ape0FQhCVlNOd9cvQKBvMxRX9K0JPVi8w0Y=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-hCETZpHHGVhPYvb4C0fh4zs+8zv4GPoixagkLZjpa9Q=";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.0.11";
    hash = "sha256-qWqFVxuXioesVftv2RVJZOnmojUvRjb7cS3Oh3oTit4=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.0.11";
    hash = "sha256-rbSgc2PIEc2c2rN6LK3qCREAX3DqA2Nq1WcLrZYsDBw=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-uNOD0EOVFgnS2fMKvMiEtI9aOw00+Pfy/H+qucAQlPc=";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "7.1.2";
    hash = "sha256-EBVWd0gyU8QM23xclTQAHE/yGbXvHKqZfZ80b1VHuiU=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.1.0";
    hash = "sha256-V6oyQFwWb8NvGxAwvzWnhPxy9dKOfj/XBM3tEC5aHrw=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression";
    version = "4.3.0";
    hash = "sha256-f5PrQlQgj5Xj2ZnHxXW8XiOivaBvfqDao9Sb6AVinyA=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.3.0";
    hash = "sha256-WQl+JgWs+GaRMeiahTFUbrhlXIHapzcpTFXbRvAtvvs=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-vNIYnvlayuVj0WfRfYKpDrhDptlhp1pN8CYmlVd2TXw=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.3.0";
    hash = "sha256-LMnfg8Vwavs9cMnq9nNH8IWtAtSfk0/Fy4s4Rt9r1kg=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.3";
    hash = "sha256-v+FOmjRRKlDtDW6+TfmyMiiki010YGVTa0EwXu9X7ck=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "9.0.8";
    hash = "sha256-dO84rUcpDgj6k8rTZq3Kmy/y+6c/cP1Fa1dsCV9JIlA=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.1.0";
    hash = "sha256-ZQpFtYw5N1F1aX0jUK3Tw+XvM5tnlnshkTCNtfVA794=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    hash = "sha256-R5uiSL3l6a3XrXSSL6jz+q/PcyVQzEAByiuXZNSqD/A=";
  })
  (fetchNuGet {
    pname = "System.Linq.Async";
    version = "6.0.3";
    hash = "sha256-i+2XnsOJnD7R/vCFtadp+lwrkDNAscANes2Ur0MSTl8=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.1.0";
    hash = "sha256-7zqB+FXgkvhtlBzpcZyd81xczWP0D3uWssyAGw3t7b4=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.3.0";
    hash = "sha256-+3pvhZY7rip8HCbfdULzjlC9FPZFpYoQxhkcuFm2wk8=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.0";
    hash = "sha256-YOz1pCR4RpP1ywYoJsgXnVlzsWtC2uYKQJTg0NnFXtE=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.3.0";
    hash = "sha256-UoBB7WPDp2Bne/fwxKF0nE8grJ6FzTMXdT/jfsphj8Q=";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-MY7Z6vOtFMbEKaLW9nOSZeAjcWpwCtdO7/W1mkGZBzE=";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.3.0";
    hash = "sha256-il7dr5VT/QWDg/0cuh+4Es2u8LY//+qqiY9BZmYxSus=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.0.12";
    hash = "sha256-MudZ/KYcvYsn2cST3EE049mLikrNkmE7QoUoYKKby+s=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.3.0";
    hash = "sha256-gtmRkWP2Kwr3nHtDh0yYtce38z1wrGzb6fjm4v8wN6Q=";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "6.0.0";
    hash = "sha256-hXB18OsiUHSCmRF3unAfdUEcbXVbG6/nZxcyz13oe9Y=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.1.0";
    hash = "sha256-idZHGH2Yl/hha1CM4VzLhsaR8Ljo/rV7TYe7mwRJSMs=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.0.1";
    hash = "sha256-F1MvYoQWHCY89/O4JBwswogitqVvKuVfILFqA7dmuHk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.0.1";
    hash = "sha256-YG+eJBG5P+5adsHiw/lhJwvREnvdHw6CJyS8ZV4Ujd0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.0.1";
    hash = "sha256-uVvNOnL64CPqsgZP2OLqNmxdkZl6Q0fTmKmv9gcBi+g=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.0.1";
    hash = "sha256-NsfmzM9G/sN3H8X2cdnheTGRsh7zbRzvegnjDzDH/FQ=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "6.0.1";
    hash = "sha256-id27sU4qIEIpgKenO5b4IHt6L1XuNsVe4TR9TKaLWDo=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.0.1";
    hash = "sha256-SFSfpWEyCBMAOerrMCOiKnpT+UAWTvRcmoRquJR6Vq0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.1.0";
    hash = "sha256-R0YZowmFda+xzKNR4kKg7neFoE30KfZwp/IwfRSKVK4=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.0.1";
    hash = "sha256-cZ2/3/fczLjEpn6j3xkgQV9ouOVjy4Kisgw5xWw9kSw=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.1.0";
    hash = "sha256-FViNGM/4oWtlP6w0JC0vJU+k9efLKZ+yaXrnEeabDQo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.1";
    hash = "sha256-R9T68AzS1PJJ7v6ARz9vo88pKL1dWqLOANg4pkQjkA0=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.3.0";
    hash = "sha256-aMJRpXIgk+E2vIQooc/slTwhkE2KVfcFyxTeG5RmPZE=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "5.0.0";
    hash = "sha256-neARSpLPUzPxEKhJRwoBzhPxK+cKIitLx7WBYncsYgo=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.1.0";
    hash = "sha256-X7DZ5CbPY7jHs20YZ7bmcXs9B5Mxptu/HnBUvUnNhGc=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-wLDHmozr84v1W2zYCWYxxj0FR0JDYHSVRaRuDm0bd/o=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.0.1";
    hash = "sha256-j2QgVO9ZOjv7D1het98CoFpjoYgxjupuIhuBUmLLH7w=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.1.0";
    hash = "sha256-QceAYlJvkPRJc/+5jR+wQpNNI3aqGySWWSO30e/FfQY=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.3.0";
    hash = "sha256-MYpl6/ZyC6hjmzWRIe+iDoldOMW1mfbwXsduAnXIKGA=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.3.0";
    hash = "sha256-P5jHCgMbgFMYiONvzmaKFeOqcAIDPu/U8bOVrNPYKqc=";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    hash = "sha256-ueSG+Yn82evxyGBnE49N4D+ngODDXgornlBtQ3Omw54=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.3.0";
    hash = "sha256-tAJvNSlczYBJ3Ed24Ae27a55tq/n4D3fubNQdwcKWA8=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.3.0";
    hash = "sha256-Yuge89N6M+NcblcvXMeyHZ6kZDfwBv3LPMDiF8HhJss=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "9.0.8";
    hash = "sha256-C89Blahc5sS8EK0fb1dd2Dbi+WIXoC18Y6msr4H4ZCA=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.3.0";
    hash = "sha256-fnFi7B3SnVj5a+BbgXnbjnGNvWrCEU6Hp/wjsjWz318=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "9.0.8";
    hash = "sha256-2My/dEWSuQ9SRGc4USEbZj25mafyORGjOS7CJguOc68=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.3.0";
    hash = "sha256-MG3V/owDh273GCUPsGGraNwaVpcydupl3EtPXj6TVG0=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Xml";
    version = "9.0.8";
    hash = "sha256-Sr4p1Hyrv9Rj7Lcb80GhLfBbbMf1ZhOdernCOa3otmk=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    hash = "sha256-CBOQwl9veFkrKK2oU8JFFEiKIh/p+aJO+q9Tc2Q/89Y=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.0.11";
    hash = "sha256-PEailOvG05CVgPTyKLtpAgRydlSHmtd5K0Y8GSHY2Lc=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "6.0.0";
    hash = "sha256-nGc2A6XYnwqGcq8rfgTRjGr+voISxNe/76k2K36coj4=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-vufHXg8QAKxHlujPHHcrtGwAqFmsCD6HKjfDAiHyAYc=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    hash = "sha256-IUQkQkV9po1LC0QsqrilqwNzPvnc+4eVvq+hCvq8fvE=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.0";
    hash = "sha256-XFcCHMW1u2/WujlWNHaIWkbW1wn8W4kI0QdrwPtWmow=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.3.0";
    hash = "sha256-VLCk1D1kcN2wbAe3d0YQM/PqCsPHOuqlBY1yd2Yo+K0=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.3.1";
    hash = "sha256-DxsEZ0nnPozyC1W164yrMUXwnAdHShS9En7ImD/GJMM=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.0.11";
    hash = "sha256-mob1Zv3qLQhQ1/xOLXZmYqpniNUMCfn02n8ZkaAhqac=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "6.0.0";
    hash = "sha256-klGYnsyrjvXaGeqgfnMf/dTAMNtcHY+zM4Xh6v2JfuE=";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "8.0.0";
    hash = "sha256-c5TYoLNXDLroLIPnlfyMHk7nZ70QAckc/c7V199YChg=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.0.11";
    hash = "sha256-5SLxzFg1df6bTm2t09xeI01wa5qQglqUwwJNlQPJIVs=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "8.0.0";
    hash = "sha256-Q6fPtMPNW4+SDKCabJzNS+dw4B04Oxd9sHH505bFtQo=";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.3.0";
    hash = "sha256-pmhslmhQhP32TWbBzoITLZ4BoORBqYk25OWbru04p9s=";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.4.0";
    hash = "sha256-LqpI3bSaXqVPqfEdfsWE2qX9tzFV6VPU6x4A/fVzzfM=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.3.0";
    hash = "sha256-QQ8KgU0lu4F5Unh+TbechO//zaAGZ4MfgvW72Cn1hzA=";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.3.0";
    hash = "sha256-rWtdcmcuElNOSzCehflyKwHkDRpiOhJJs8CeQ0l1CCI=";
  })
  (fetchNuGet {
    pname = "TestableIO.System.IO.Abstractions.Wrappers";
    version = "22.0.15";
    hash = "sha256-KoGuXGzecpf4rTmEth4/2goVFFR9V2aj+iibfZxpR7U=";
  })
  (fetchNuGet {
    pname = "Testably.Abstractions.FileSystem.Interface";
    version = "9.0.0";
    hash = "sha256-6JW+qDtqQT9StP4oTR7uO0NnmVc2xcjSZ6ds2H71wtg=";
  })
  (fetchNuGet {
    pname = "Tmds.LibC";
    version = "0.2.0";
    hash = "sha256-vUIF8ZWGQ3cIT7cWIttbhHM4RliU9uly/BQfezLm5/Q=";
  })
  (fetchNuGet {
    pname = "Websocket.Client";
    version = "5.2.0";
    hash = "sha256-5sVfK1iHclxunfm0ioSFFyo5tG8lPfchClBi4YgeJT4=";
  })
  (fetchNuGet {
    pname = "YamlDotNet";
    version = "16.0.0";
    hash = "sha256-wCKzDkAuIpQ65MKe39Zn/K8iX8FKdkw49OHIi7m6GHU=";
  })
  (fetchNuGet {
    pname = "ZstdSharp.Port";
    version = "0.8.6";
    hash = "sha256-rc3YWP80fykqujDsD72SXOA1tBDoy2KrvVETOC8eTx8=";
  })
]
