# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Antlr4.Runtime.Standard";
    version = "4.11.1";
    sha256 = "0mp0ydgdqnf1g8v5ll9ifay4xc2hv9grky1qlzrmkfi7wscpas5a";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI";
    version = "6.0.5";
    sha256 = "0b3bgmfa6y6qrygn3ml3hnwycx6r09kv4h0wrwk2jxr9a8daw7vf";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI.Client";
    version = "6.0.5";
    sha256 = "09s5z1m501jmki7983laid5dgkrm1qgdx4ljawv52dn1npgh8vzm";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI.Core";
    version = "6.0.5";
    sha256 = "07hkiw81kw8281rgnvwqm0202pmk1mxgy7n2dzh5fx5fn10vdy2a";
  })
  (fetchNuGet {
    pname = "AspNetCore.HealthChecks.UI.InMemory.Storage";
    version = "6.0.5";
    sha256 = "04djdw7mhch2j9ahxd26fgzn3c3lxyhnyrvsjqvsmgm1dkqwimcs";
  })
  (fetchNuGet {
    pname = "AutoMapper";
    version = "9.0.0";
    sha256 = "1dv0p7h470nb733yqjjqf0ng3axzrl4vshr2npqkzwp2mfv90lsb";
  })
  (fetchNuGet {
    pname = "Castle.Core";
    version = "5.0.0";
    sha256 = "1f6qd0zy4s3dvi4f3sp9f3fx25rj16sib9hcha456z8i5nrlnix3";
  })
  (fetchNuGet {
    pname = "Ckzg.Bindings";
    version = "0.1.2.501";
    sha256 = "1iklv8zzd77dlly95a8cmz1haf5nd9v23hxfkb65njhiw83msw14";
  })
  (fetchNuGet {
    pname = "Colorful.Console";
    version = "1.2.15";
    sha256 = "03g8367lchh42jn6iidj10dnlibr8wlbdarsx7zanp3f4z7lf4rw";
  })
  (fetchNuGet {
    pname = "ConcurrentHashSet";
    version = "1.3.0";
    sha256 = "04jydfpzv1pwn60m23fl3qgdsvmcd2nrnn68rviixc031j7bhgp6";
  })
  (fetchNuGet {
    pname = "coverlet.collector";
    version = "3.2.0";
    sha256 = "1qxpv8v10p5wn162lzdm193gdl6c5f81zadj8h889dprlnj3g8yr";
  })
  (fetchNuGet {
    pname = "coverlet.msbuild";
    version = "3.2.0";
    sha256 = "0lyw70xgri3jqxzd06s077p8wymislljsyrsyn081pb0xc20vd00";
  })
  (fetchNuGet {
    pname = "Crc32.NET";
    version = "1.2.0";
    sha256 = "0qaj3192k1vfji87zf50rhydn5mrzyzybrs2k4v7ap29k8i0vi5h";
  })
  (fetchNuGet {
    pname = "DiffEngine";
    version = "10.0.0";
    sha256 = "1ra8kj3ax6phmz5312zpasw6zwvrm1fw34fsyah2bx0anmhiqhrf";
  })
  (fetchNuGet {
    pname = "DnsClient";
    version = "1.7.0";
    sha256 = "0q6sl7nrwks1xl23z0r097g7b95d0j59r08c21dpbf13fyai9mw5";
  })
  (fetchNuGet {
    pname = "dotnet-xunit";
    version = "2.3.1";
    sha256 = "0w1zslkig6qk6rhw6ckfy331rnbfbnxr0gdy2pxgnc8rz2fj2s54";
  })
  (fetchNuGet {
    pname = "EmptyFiles";
    version = "2.8.0";
    sha256 = "0lxx4qxhf41c1yjz0pn73n0xd536zi1cx5d5j6bmgg6jlz8646sj";
  })
  (fetchNuGet {
    pname = "FastEnum";
    version = "1.8.0";
    sha256 = "0czqiqq7v02977wy0mr33z06xlfnw805s3051sqqvacil1n4adcv";
  })
  (fetchNuGet {
    pname = "FluentAssertions";
    version = "6.0.0";
    sha256 = "1p5m89rbaqbrn8vr3bs79j8fcdhasn6n3bcxhajp2f5p4mpzv83f";
  })
  (fetchNuGet {
    pname = "FluentAssertions";
    version = "6.10.0";
    sha256 = "0agw9snp59hzsdy8plwj6byiy20xd5l3zx5627yn44m4lh8md17q";
  })
  (fetchNuGet {
    pname = "FluentAssertions.Json";
    version = "6.1.0";
    sha256 = "0mski8r35y4kp0r2q66v5zjck476xccqvaky77kcpjyf8vmbc5d6";
  })
  (fetchNuGet {
    pname = "Fractions";
    version = "4.0.1";
    sha256 = "0mdfpxqxh5ldiv8pfizs5pd4in0lqcpc4mnqqpx6fi7vmkcnl04p";
  })
  (fetchNuGet {
    pname = "FSharp.Core";
    version = "6.0.2";
    sha256 = "0q4z31i6vw38b6anwjfzxy3ncdazymddi1xyfskkb0s4744ilpi5";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.22.0";
    sha256 = "1wjxxlqdrjjb0f3py8sbgsivqms8d22m7xk1zx68gfmyih671in7";
  })
  (fetchNuGet {
    pname = "Google.Protobuf.Tools";
    version = "3.22.0";
    sha256 = "19sq1zxfv05vx0lrnbnfzg3r1s4j4kcig8z0bnw2jjhcqna3ia60";
  })
  (fetchNuGet {
    pname = "Grpc";
    version = "2.46.6";
    sha256 = "1zj2j7h97qdns14z3ilfgqx3kir9p5a05kwsvyz3hpnx2z6j3ysj";
  })
  (fetchNuGet {
    pname = "Grpc.Core";
    version = "2.46.6";
    sha256 = "1lyy2l8xxjnfvrf9jxdffms70qqjlz41s0k3y53w637n5qif7hgz";
  })
  (fetchNuGet {
    pname = "Grpc.Core.Api";
    version = "2.46.6";
    sha256 = "1c5h83h2snvwvdzyiinqcls01jx87n7jgma3mvhhv01j2q8qqfhy";
  })
  (fetchNuGet {
    pname = "Grpc.Tools";
    version = "2.51.0";
    sha256 = "016rs4gz85hnbz6bzymgy7mra08782v3j3lz8b6jq60w0543ngx9";
  })
  (fetchNuGet {
    pname = "Humanizer.Core";
    version = "2.8.26";
    sha256 = "1v8xd12yms4qq1md4vh6faxicmqrvahqdd7sdkyzrphab9v44nsm";
  })
  (fetchNuGet {
    pname = "IdentityModel";
    version = "4.1.0";
    sha256 = "1mpidh18f780g9hrmr7qfzfv2navh7kl0pn107vs74bcl0h1d6x4";
  })
  (fetchNuGet {
    pname = "IdentityModel.OidcClient";
    version = "3.1.2";
    sha256 = "008h1k9lyxg3a96ixz4k348z2d9sc7f0r2f64maw3j96mkimp2yc";
  })
  (fetchNuGet {
    pname = "Jint";
    version = "2.11.58";
    sha256 = "1nw3mbr1sl198lkwl6bsnfajd3rgw83p63vgi1dackfvx6haywnv";
  })
  (fetchNuGet {
    pname = "KubernetesClient";
    version = "4.0.26";
    sha256 = "16sk8vya2238yxsbz99dsi74vfvdri51n03k589b0z80738r4mvj";
  })
  (fetchNuGet {
    pname = "Libuv";
    version = "1.9.0";
    sha256 = "0ag6l9h1h4knf3hy1fjfrqm6mavr9zw35i0qrnnm8la4mdbcnd0f";
  })
  (fetchNuGet {
    pname = "MathNet.Numerics";
    version = "5.0.0";
    sha256 = "0nlrl0rp7h665nafx0g42rqfxmm0pyvk3ydr2y4spilfrra44wj4";
  })
  (fetchNuGet {
    pname = "MathNet.Numerics.FSharp";
    version = "5.0.0";
    sha256 = "06x8ppnzlzmb1gswvygqp8n7x0p1jpx76f7g29h30ck6jzqf3xm4";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Cryptography.Internal";
    version = "7.0.3";
    sha256 = "04vxj2m5crxmh9q8k1x0yc1bx85yqicdsj6q4q6fq6jgx0rkk3pi";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.DataProtection";
    version = "7.0.3";
    sha256 = "02z4v4xwidwlp24gmlphnlh7wibzd622frgmpjcsz2j9xpk3ga5y";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.DataProtection.Abstractions";
    version = "7.0.3";
    sha256 = "1r8csi3zslv1xl7rpnjh97zf88lf653qsai6njsa3jw3icyxbqln";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.DataProtection.Extensions";
    version = "7.0.3";
    sha256 = "0wf97vbm4y78zd4zhwx8gj6jq7mp0ri1ddjwj2icfa3jn9m7cwwd";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Http.Abstractions";
    version = "2.2.0";
    sha256 = "13s8cm6jdpydxmr0rgmzrmnp1v2r7i3rs7v9fhabk5spixdgfy6b";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Http.Extensions";
    version = "2.2.0";
    sha256 = "118gp1mfb8ymcvw87fzgjqwlc1d1b0l0sbfki291ydg414cz3dfn";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Http.Features";
    version = "2.2.0";
    sha256 = "0xrlq8i61vzhzzy25n80m7wh2kn593rfaii3aqnxdsxsg6sfgnx1";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.WebSockets";
    version = "2.2.1";
    sha256 = "0gzikr1z2fdz8nzy1m969jsrk2h97ld1hzgmbc6f036qmhiq26hr";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    sha256 = "15gqy2m14fdlvy1g59207h5kisznm355kbw010gy19vh47z8gpz3";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "1.1.0";
    sha256 = "08r667hj2259wbim1p3al5qxkshydykmb7nd9ygbjlg4mmydkapc";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "1.3.0";
    sha256 = "097qi36jhyllpqj313nxzwc64a4f65p014gaj6fz4z5jcphkkk15";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "1.3.0";
    sha256 = "0vpslncd5lk88ijb42qbp88dfrd0fg4kri44w6jpmxb3fcqazais";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.VisualBasic";
    version = "1.3.0";
    sha256 = "186chky80rryhzh5dh8j318ghyvn1a7r2876rlyadxdrs7aqv0ll";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.4.1";
    sha256 = "0bf68gq6mc6kzri4zi8ydc0xrazqwqg38bhbpjpj90zmqc28kari";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.0.1";
    sha256 = "0zxc0apx1gcx361jlq8smc9pfdgmyjh6hpka8dypc9w23nlsh6yj";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.3.0";
    sha256 = "0gw297dgkh0al1zxvgvncqs0j15lsna9l1wpqas4rflmys440xvb";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.5.0";
    sha256 = "01i28nvzccxbqmiz217fxs6hnjwmd5fafs37rd49a6qp53y6623l";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    sha256 = "0gd67zlw554j098kabg887b5a6pq9kzavpa3jjy5w53ccjzjfy8j";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite.Core";
    version = "2.0.0-preview1-final";
    sha256 = "0zxd5xy2qfbjgwx0q7xgagmxsacgfwqk5y0rah0dirv7fngpjbq1";
  })
  (fetchNuGet {
    pname = "Microsoft.Data.Sqlite.Core";
    version = "6.0.7";
    sha256 = "0r5njqyl10dv0akwl5y32ik0rpzs9lwj151j6ayz358pn4x26akk";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore";
    version = "6.0.7";
    sha256 = "1wcjjn70v8cyy5flga0nlnhg973s6pzb3rpnzv905ix3g70zdp4k";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Abstractions";
    version = "6.0.7";
    sha256 = "0xhkh9k3xpgjdsizg1wdncwz4rdjvffq3x0sfcarscmg2j5fa4yj";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Analyzers";
    version = "6.0.7";
    sha256 = "0fdh0w5c51kkpvh1p5f0dn90kikh3zdyc1k4hjvv1z8kr603nd1b";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Design";
    version = "6.0.7";
    sha256 = "0mdb2gqmb94sw38cpqm972vdhh88n7q81xhq4gq771hp2wspn5ap";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.InMemory";
    version = "6.0.7";
    sha256 = "1bjgb8yzpl0qlkz172n3v5ihqjmy8hlirf0ffc05g3i0nlx1cl2j";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Relational";
    version = "2.0.0-preview1-final";
    sha256 = "040pmi5qxqrjaxkqxivsxxly2vxxidbyqsjp4b6lgzwv442ybxvs";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Relational";
    version = "6.0.7";
    sha256 = "1kx0ac7jgf8nmp5nra4cd6h2xbwvb3zkyzx7cds60y1j9nm7lx1g";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Relational.Design";
    version = "2.0.0-preview1-final";
    sha256 = "0fk2nvkayx7n2c9ch8jby63a11x5hmzxria6waxgx88kg16x8748";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Sqlite";
    version = "6.0.7";
    sha256 = "1mam4qg6yq6qnlkx3i45gs3nwgd7njfm9r5gjs1p9wm6bm953dad";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Sqlite.Core";
    version = "2.0.0-preview1-final";
    sha256 = "1dfqs2w1m3lsxn6cyqpfbsianafig19wf4ra16vd4aflzck8bq3l";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Sqlite.Core";
    version = "6.0.7";
    sha256 = "15l36dgq6rzvgx7i9g9jm3298p9g1pdahwa2dxblmm0gzsp65wpl";
  })
  (fetchNuGet {
    pname = "Microsoft.EntityFrameworkCore.Sqlite.Design";
    version = "2.0.0-preview1-final";
    sha256 = "1cn9gqvq0p5rin9dzly3h2s2z0vadbw3yp7wlsga9ql2na4slc8a";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Caching.Abstractions";
    version = "6.0.0";
    sha256 = "0qn30d3pg4rx1x2k525jj4x5g1fxm2v5m0ksz2dmk1gmqalpask8";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Caching.Memory";
    version = "6.0.1";
    sha256 = "0ra0ldbg09r40jzvfqhpb3h42h80nafvka9hg51dja32k3mxn5gk";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.CommandLineUtils";
    version = "1.1.1";
    sha256 = "0g61kphvdira64g543qlf610sia02scdmki1566d5kr6v390qvbq";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "2.1.0";
    sha256 = "04rjl38wlr1jjjpbzgf64jp0ql6sbzbil0brwq9mgr3hdgwd7vx2";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "3.1.0";
    sha256 = "1rszgz0rd5kvib5fscz6ss3pkxyjwqy0xpd4f2ypgzf5z5g5d398";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "7.0.0";
    sha256 = "0n1grglxql9llmrsbbnlz5chx8mxrb5cpvjngm0hfyrkgzcwz90d";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "2.1.0";
    sha256 = "03gzlr3z9j1xnr1k6y91zgxpz3pj27i3zsvjwj7i8jqnlqmk7pxd";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "3.1.0";
    sha256 = "1f7h52kamljglx5k08ccryilvk6d6cvr9c26lcb6b2c091znzk0q";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "6.0.0";
    sha256 = "0w6wwxv12nbc3sghvr68847wc9skkdgsicrz3fx4chgng1i3xy0j";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "7.0.0";
    sha256 = "1as8cygz0pagg17w22nsf6mb49lr2mcl1x8i3ad1wi8lyzygy1a3";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "2.1.0";
    sha256 = "0x1888w5ypavvszfmpja9krgc64527prs75vm8xbf9fv3rgsplql";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "3.1.0";
    sha256 = "13jj7jxihiswmhmql7r5jydbca4x5qj6h7zq10z17gagys6dc7pw";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "7.0.0";
    sha256 = "1qifb1pv7s76lih8wnjk418wdk4qwn87q2n6dx54knfvxai410bl";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "3.1.0";
    sha256 = "1xc61dy07bn2q73mx1z3ylrw80xpa682qjby13gklnqq636a3gab";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "5.0.0";
    sha256 = "15sdwcyzz0qlybwbdq854bn3jk6kx7awx28gs864c4shhbqkppj4";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "6.0.0";
    sha256 = "1wlhb2vygzfdjbdzy7waxblmrx0q3pdcqvpapnpmq9fcx5m8r6w1";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "7.0.0";
    sha256 = "121zs4jp8iimgbpzm3wsglhjwkc06irg1pxy8c1zcdlsg34cfq1p";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "2.1.0";
    sha256 = "0c0cx8r5xkjpxmcfp51959jnp55qjvq28d9vaslk08avvi1by12s";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "2.2.0";
    sha256 = "1jyzfdr9651h3x6pxwhpfbb9mysfh8f8z1jvy4g117h9790r9zx5";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "3.1.0";
    sha256 = "1pvms778xkyv1a3gfwrxnh8ja769cxi416n7pcidn9wvg15ifvbh";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "5.0.0";
    sha256 = "17cz6s80va0ch0a6nqa1wbbbp3p8sqxb96lj4qcw67ivkp2yxiyj";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "6.0.0";
    sha256 = "1vi67fw7q99gj7jd64gnnfr4d2c0ijpva7g9prps48ja6g91x6a9";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "7.0.0";
    sha256 = "181d7mp9307fs17lyy42f8cxnjwysddmpsalky4m0pqxcimnr6g7";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "6.0.0";
    sha256 = "08c4fh1n8vsish1vh7h73mva34g0as4ph29s4lvps7kmjb4z64nl";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.HealthChecks";
    version = "6.0.7";
    sha256 = "14jqhm15gg03smjx74vfcqmviw42yb9lqfdy0h8824mls350cb73";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions";
    version = "6.0.7";
    sha256 = "1bv9p3yw4icz602pn95hk8640s16ysqgp2c2lj2znrz7iay2jg4m";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "2.2.0";
    sha256 = "1f83ffb4xjwljg8dgzdsa3pa0582q6b4zm0si467fgkybqzk3c54";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "6.0.0";
    sha256 = "1fbqmfapxdz77drcv1ndyj2ybvd2rv4c9i9pgiykcpl4fa6dc65q";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "7.0.0";
    sha256 = "0ff20yklyjgyjzdyv7sybczgqhgd557m05dbwxzjznr0x41b180d";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "6.0.0";
    sha256 = "1mwjx6li4a82nb589763whpnhf5hfy1bpv1dzqqvczb1lhxhzhlj";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "7.0.0";
    sha256 = "1h5szfsr1dalsvdj9c18y6362853chisfns0hfpsq44hz0pr8j9q";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Http";
    version = "3.1.0";
    sha256 = "02ipxf75rqzsbmmy5ka44hh8krmxgky9mdxmh8f7fkbclpg2s6cy";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Http";
    version = "6.0.0";
    sha256 = "1wxsqvfy2arbwk0nhambjprazim6ynrb23r1hr5vk4gv10i26m95";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "2.1.0";
    sha256 = "0dii8i7s6libfnspz2xb96ayagb4rwqj2kmr162vndivr9rmbm06";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "3.1.0";
    sha256 = "1d3yhqj1rav7vswm747j7w8fh8paybji4rz941hhlq4b12mfqfh4";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "5.0.0";
    sha256 = "1qa1l18q2jh9azya8gv1p8anzcdirjzd9dxxisb4911i9m1648i3";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "6.0.0";
    sha256 = "0fd9jii3y3irfcwlsiww1y9npjgabzarh33rn566wpcz24lijszi";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "7.0.0";
    sha256 = "1bqd3pqn5dacgnkq0grc17cgb2i0w8z1raw12nwm3p3zhrfcvgxf";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "2.1.0";
    sha256 = "1gvgif1wcx4k6pv7gc00qv1hid945jdywy1s50s33q0hfd91hbnj";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "2.2.0";
    sha256 = "02w7hp6jicr7cl5p456k2cmrjvvhm6spg5kxnlncw3b72358m5wl";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "3.1.0";
    sha256 = "1zyalrcksszmn9r5xjnirfh7847axncgzxkk3k5srbvlcch8fw8g";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "5.0.0";
    sha256 = "1yza38675dbv1qqnnhqm23alv2bbaqxp0pb7zinjmw8j2mr5r6wc";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "6.0.0";
    sha256 = "0b75fmins171zi6bfdcq1kcvyrirs8n91mknjnxy4c3ygi1rrnj0";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "6.0.1";
    sha256 = "17w4x7iakwpn7crg4yk5qkkv5gkx0lfl6anwwhb1554pwak5cwdz";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "7.0.0";
    sha256 = "1gn7d18i1wfy13vrwhmdv1rmsb4vrk26kqdld4cgvh77yigj90xs";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "7.0.0";
    sha256 = "1f5fhpvzwyrwxh3g1ry027s4skmklf6mbm2w0p13h0x6fbmxcb24";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "7.0.0";
    sha256 = "1m8ri2m3vlv9vzk0068jkrx0vkk4sqmk1kxmn8pc3wys38d38qaf";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ObjectPool";
    version = "7.0.0";
    sha256 = "15lz0qk2gr2q52i05ip51dzm9p4hzqlrammkc0hv2ng6g0z72697";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ObjectPool";
    version = "7.0.3";
    sha256 = "1dzcmxcjw2z4czv16x56jnjh6gcrzcahqrpzkkfzcvrzhak0x6p6";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "2.1.0";
    sha256 = "0w9644sryd1c6r3n4lq2cgd5pn6jl3k5m38a05m7vjffa4m2spd2";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "2.2.0";
    sha256 = "1b20yh03fg4nmmi3vlf6gf13vrdkmklshfzl3ijygcs4c2hly6v0";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "3.1.0";
    sha256 = "0akccwhpn93a4qrssyb3rszdsp3j4p9hlxbsb7yhqb78xydaqhyh";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "5.0.0";
    sha256 = "1rdmgpg770x8qwaaa6ryc27zh93p697fcyvn5vkxp0wimlhqkbay";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "6.0.0";
    sha256 = "008pnk2p50i594ahz308v81a41mbjz9mwcarqhmrjpl2d20c868g";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "7.0.0";
    sha256 = "0b90zkrsk5dw3wr749rbynhpxlg4bgqdnd7d5vdlw2g9c7zlhgx6";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "7.0.1";
    sha256 = "0ghz4y4gxnf2vw8yvhz9nkw21p6q2qqwh19phkk1xwxywyilr3mq";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "7.0.0";
    sha256 = "1liyprh0zha2vgmqh92n8kkjz61zwhr7g16f0gmr297z2rg1j5pj";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "2.1.0";
    sha256 = "1r9gzwdfmb8ysnc4nzmyz5cyar1lw0qmizsvrsh252nhlyg06nmb";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "2.2.0";
    sha256 = "0znah6arbcqari49ymigg3wiy2hgdifz8zsq8vdc3ynnf45r7h0c";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "3.1.0";
    sha256 = "1w1y22njywwysi8qjnj4m83qhbq0jr4mmjib0hfawz6cwamh7xrb";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "5.0.0";
    sha256 = "0swqcknyh87ns82w539z1mvy804pfwhgzs97cr3nwqk6g5s42gd6";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "6.0.0";
    sha256 = "1kjiw6s4yfz9gm7mx3wkhp06ghnbs95icj9hi505shz9rjrg42q2";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "7.0.0";
    sha256 = "1b4km9fszid9vp2zb3gya5ni9fn8bq62bzaas2ck2r7gs0sdys80";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Abstractions";
    version = "6.27.0";
    sha256 = "053c1pkx9bnb9440f5rkzbdv99wgcaw95xnqjp09ncd2crh8kakp";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "5.6.0";
    sha256 = "0wfzns7w8rwlz815yw07apxc9qhcmwbaz53l2rwwcrgh1r6fgchz";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "6.27.0";
    sha256 = "103qvpahmn1x8yxj0kc920s27xbyjr15z8lf5ikrsrikalb5yjx9";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "5.6.0";
    sha256 = "0sp2r8sgjz2jqnr203scyxr2zjzygi4f0hhjyrilwbjp8szvb24v";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "6.27.0";
    sha256 = "1c3b0bkmxa24bvzi16jc7lc1nifqcq4jg7ild973bb8mivicagzv";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "5.6.0";
    sha256 = "12warwfv4wpp33i9mg8dmw60i57sfc736sa6sw200w9g4j5rgh0w";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "6.27.0";
    sha256 = "0h51vdcz6pkv4ky2ygba4vks56rskripqb3fjz95ym0l0xg20s1a";
  })
  (fetchNuGet {
    pname = "Microsoft.Net.Http.Headers";
    version = "2.2.0";
    sha256 = "0w6lrk9z67bcirq2cj2ldfhnizc6id77ba6i30hjzgqjlyhh1gx5";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.4.1";
    sha256 = "02p1j9fncd4fb2hyp51kw49d0dz30vvazhzk24c9f5ccc00ijpra";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App";
    version = "1.0.0";
    sha256 = "0i09cs7a7hxn9n1nx49382csvc7560j4hbxr2c8bwa69nhf2rrjp";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHost";
    version = "1.0.1";
    sha256 = "1qr4gnzlpwzv8jr7ijmdg13x2s9m35g4ma0bh18kci4ml7h9jb6a";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHostPolicy";
    version = "1.0.1";
    sha256 = "0vbqww1bmlkz7xq05zxykv27xdrkl6nrjhs1iiszaa9ivf7nklz1";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.DotNetHostResolver";
    version = "1.0.1";
    sha256 = "109zs3bqhzh6mhbf2rfpwxmpb8fq57jr7wriyylynirsqh1lnql4";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Jit";
    version = "1.0.2";
    sha256 = "0jaan2wmg80lr0mhgfy70kb5cqjwv1a2ikmxgd0glpcxp7wr7pag";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.0.1";
    sha256 = "01al6cfxp68dscl15z7rxfw9zvhm64dncsw09a1vmdkacsa2v6lr";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    sha256 = "08vh1r12g6ykjygq5d3vq09zylgb84l63k49jc4v8faw9g93iqqm";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.1";
    sha256 = "164wycgng4mi9zqi2pnsf1pq6gccbqvw6ib916mqizgjmd8f44pj";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    sha256 = "0mwpwdflidzgzfx2dlpkvvnkgkr2ayaf0s80737h4wa35gaj11rc";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Runtime.CoreCLR";
    version = "1.0.2";
    sha256 = "1hxgsjyzh7hdgd34xwpn5s2myy1b1y9ms7xhvs6mkb75wap49bpc";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.0.1";
    sha256 = "0ppdkwy6s9p7x9jix3v4402wb171cdiibq7js7i13nxpdky7074p";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    sha256 = "193xwf33fbm0ni3idxzbr5fdq3i2dlfgihsac9jj7whj0gd902nh";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Windows.ApiSets";
    version = "1.0.1";
    sha256 = "16k8chghkr25jf49banhzl839vs8n3vbfpg4wn4idi0hzjipix78";
  })
  (fetchNuGet {
    pname = "Microsoft.Packaging.Tools";
    version = "1.0.0-preview1-25301-01";
    sha256 = "06ljw8qh5sizpximmzi55d34vlc40ng9v5kwzk73jaxi6ysnjkic";
  })
  (fetchNuGet {
    pname = "Microsoft.Rest.ClientRuntime";
    version = "2.3.10";
    sha256 = "0r7mkm9p35zbvfs93rpl78v1fgi5pnjc1lkyj72mls1q9z40cgnw";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.4.1";
    sha256 = "0s68wf9yphm4hni9p6kwfk0mjld85f4hkrs93qbk5lzf6vv3kba1";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.4.1";
    sha256 = "1n9ilq8n5rhyxcri06njkxb0h2818dbmzddwd2rrvav91647m2s4";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualBasic";
    version = "10.0.1";
    sha256 = "0q6vv9qfkbwn7gz8qf1gfcn33r87m260hsxdsk838mcbqmjz6wgc";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Azure.Containers.Tools.Targets";
    version = "1.17.0";
    sha256 = "1p2sy9br5n1i0l82mizal1igvy1r19ln0m93l3xdf6p4q9m8ahym";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.0.1";
    sha256 = "1n8ap0cmljbqskxpf8fjzn7kh1vvlndsa75k01qig26mbw97k2q7";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.3.0";
    sha256 = "0j0c1wj4ndj21zsgivsc24whiya605603kxrbiw6wkfdync464wq";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "4.0.0";
    sha256 = "1spf4m9pikkc19544p29a47qnhcd885klncahz133hbnyqbkmz9k";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    sha256 = "102hvhq2gmlcbq8y2cb7hdr2dnmjzfp2k3asr1ycwrfacwyaak7n";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "7.0.0";
    sha256 = "1bh77misznh19m1swqm3dsbji499b8xh9gk6w74sgbkarf6ni8lb";
  })
  (fetchNuGet {
    pname = "Nethermind.Crypto.Pairings";
    version = "1.0.1";
    sha256 = "1d8n97snf30iymdzjn6528655cw0skpb3jb2kywbh5hj9f2nl7mp";
  })
  (fetchNuGet {
    pname = "Nethermind.Crypto.SecP256k1";
    version = "1.0.1";
    sha256 = "0vmkv5zmr15lakcbi4ilicrk671igfw2n4nk1b6bbxdhy7vga3yw";
  })
  (fetchNuGet rec {
    pname = "Nethermind.DotNetty.Buffers";
    version = "1.0.1-preview.2";
    sha256 = "sha256-S1LLt2GPojb3WVphgLXAT51/knOa1K4RCAZD8zt1o1k=";
    url = "https://int.nugettest.org/api/v2/package/${pname}/${version}";
  })
  (fetchNuGet rec {
    pname = "Nethermind.DotNetty.Codecs";
    version = "1.0.1-preview.2";
    sha256 = "sha256-djPtw0REDNcjL+uFQZ5BwFf63GsETOsTUL9HmZvm3Pw=";
    url = "https://int.nugettest.org/api/v2/package/${pname}/${version}";
  })
  (fetchNuGet rec {
    pname = "Nethermind.DotNetty.Common";
    version = "1.0.1-preview.2";
    sha256 = "sha256-sb9uN5KDpw5BAfORVF8aB8xAkjnuA4xd14yinFDk3YU=";
    url = "https://int.nugettest.org/api/v2/package/${pname}/${version}";
  })
  (fetchNuGet rec {
    pname = "Nethermind.DotNetty.Handlers";
    version = "1.0.1-preview.2";
    sha256 = "sha256-bjMRcH6azDfYTJXaxAfaS2cfGrVZuYYMd+LX5xGBBiY=";
    url = "https://int.nugettest.org/api/v2/package/${pname}/${version}";
  })
  (fetchNuGet rec {
    pname = "Nethermind.DotNetty.Transport";
    version = "1.0.1-preview.2";
    sha256 = "sha256-MHfjnBHcrFiBpNSI+K265NTot/GLsPPGRfzwdDh4bjc=";
    url = "https://int.nugettest.org/api/v2/package/${pname}/${version}";
  })
  (fetchNuGet {
    pname = "Nethermind.Gmp";
    version = "1.0.1";
    sha256 = "1x9in44pvg2jjiqrf8q9l4qyqilcbx6hr2ywgk42gjxri27agnih";
  })
  (fetchNuGet {
    pname = "Nethermind.Numerics.Int256";
    version = "1.1.0";
    sha256 = "0zhbld37lv0lx51dr5w8gc711r5kvf18ab5fqf0nj3ahva48z965";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.0";
    sha256 = "0nmmv4yw7gw04ik8ialj3ak0j6pxa9spih67hnn1h2c38ba8h58k";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.1";
    sha256 = "1z70wvsx2d847a2cjfii7b83pjfs34q05gb037fdjikv5kbagml8";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.0";
    sha256 = "1bc4ba8ahgk15m8k4nd7x406nhi0kwqzbgjk2dmw52ss553xz7iy";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.0-preview1-25301-01";
    sha256 = "1d7rpl16sf0c4b069cs1vpzq8838v1ag2ww7qsyna8jvip7ks2zz";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    sha256 = "0fijg0w6iwap8gvzyjnndds0q4b8anwxxvik7y8vgq97dram4srb";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.2";
    sha256 = "1p9splg1min274dpz7xdfgzrwkyfd3xlkygwpr1xgjvvyjvs6b0i";
  })
  (fetchNuGet {
    pname = "Nito.Collections.Deque";
    version = "1.1.1";
    sha256 = "152564q3s0n5swfv5p5rx0ghn2sm0g2xsnbd7gv8vb9yfklv7yg8";
  })
  (fetchNuGet {
    pname = "NLog";
    version = "5.2.0";
    sha256 = "1j27wrjxjpfy10s5182d477y6qb50fdak6r0vx44bbsakmv0zv3s";
  })
  (fetchNuGet {
    pname = "NLog.Targets.Seq";
    version = "3.0.0";
    sha256 = "0g8nr46mdc447n3hbkgmhdd7k65mg4zx7ydm349ddr0pwjivcm3f";
  })
  (fetchNuGet {
    pname = "NSubstitute";
    version = "5.0.0";
    sha256 = "1iacc39nz8pzxay5fs9mzrflmr9mvwjd3lrn61yc7kmamqs87rqk";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "5.11.0";
    sha256 = "0wv26gq39hfqw9md32amr5771s73f5zn1z9vs4y77cgynxr73s4z";
  })
  (fetchNuGet {
    pname = "NUnit";
    version = "3.13.3";
    sha256 = "0wdzfkygqnr73s6lpxg5b1pwaqz9f414fxpvpdmf72bvh4jaqzv6";
  })
  (fetchNuGet {
    pname = "NUnit.Analyzers";
    version = "3.6.1";
    sha256 = "16dw5375k2wyhiw9x387y7pjgq6zms30y036qb8z7idx4lxw9yi9";
  })
  (fetchNuGet {
    pname = "NUnit3TestAdapter";
    version = "4.3.1";
    sha256 = "1j80cfrg0fflgw7wxi76mxj1wllwzcg4ck957knmjpghw5cw7lvv";
  })
  (fetchNuGet {
    pname = "Open.NAT.Core";
    version = "2.1.0.5";
    sha256 = "0f6c7m1x1kssicbi6q60jys3fnbj6zs69v37wdsmvbqgc0pvk89f";
  })
  (fetchNuGet {
    pname = "Polly";
    version = "7.2.3";
    sha256 = "1iws4jd5iqj5nlfp16fg9p5vfqqas1si0cgh8xcj64y433a933cv";
  })
  (fetchNuGet {
    pname = "Portable.BouncyCastle";
    version = "1.8.1.3";
    sha256 = "1lv1ljaz8df835jgmp3ny1xgqqjf1s9f25baw7bf8d24qlf25i2g";
  })
  (fetchNuGet {
    pname = "Portable.BouncyCastle";
    version = "1.9.0";
    sha256 = "0kphjwz4hk2nki3b4f9z096xzd520nrpvi3cjib8fkjk6zhwrr8q";
  })
  (fetchNuGet {
    pname = "prometheus-net";
    version = "4.1.1";
    sha256 = "0n016rxlz00xrw1jrikwr6h221rrw96h13d0823mfb5375rdi8rx";
  })
  (fetchNuGet {
    pname = "prometheus-net";
    version = "8.0.0";
    sha256 = "1ac527simsknkbanzdvjkw0gqhp52m1d44f3nfhzsdxhc8yp963r";
  })
  (fetchNuGet {
    pname = "prometheus-net.AspNetCore";
    version = "8.0.0";
    sha256 = "1knkcjr9izxjnpn3f0prhk3b78jjdlfs6mfxlwigz2yzw83x4zm8";
  })
  (fetchNuGet {
    pname = "ReadLine";
    version = "2.0.1";
    sha256 = "1bc7aiyh99kkf4indrqzlf3y6517xhxh02nizybkp4hbxga1caih";
  })
  (fetchNuGet {
    pname = "RichardSzalay.MockHttp";
    version = "6.0.0";
    sha256 = "1bmsd8ivwk86mar047jal98s2cmxx69pxpw9q2b59a4lmkp9vn2m";
  })
  (fetchNuGet {
    pname = "RocksDB";
    version = "8.0.0.37755";
    sha256 = "0msla7nanr8i9ylf0n8c5z692a21fsm7vkjw3y9s6jfc0rqsjal7";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    sha256 = "0bv5qgm6vr47ynxqbnkc7i797fdi8gbjjxii173syrx14nmrkwg0";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tools";
    version = "4.3.0";
    sha256 = "1wl76vk12zhdh66vmagni66h5xbhgqq7zkdpgw21jhxhvlbcl8pk";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tracing";
    version = "4.3.0";
    sha256 = "00j6nv2xgmd3bi347k00m7wr542wjlig53rmj28pmw7ddcn97jbn";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    sha256 = "1daqf33hssad94lamzg01y49xwndy2q97i2lrb7mgn28656qia1x";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization.Calendars";
    version = "4.3.0";
    sha256 = "1ghhhk5psqxcg6w88sxkqrc35bxcz27zbqm2y5p5298pv3v7g201";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    sha256 = "0l8xz8zn46w4d10bcn3l4yyn4vhb3lrj2zw8llvz7jk14k4zps5x";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    sha256 = "02c9h3y35pylc0zfq3wcsvc5nqci95nrkq0mszifc0sjx7xrzkly";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    sha256 = "0zyri97dfc5vyaz9ba65hjj1zbcrzaffhsdlpxc9bh09wy22fq33";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    sha256 = "0x1mm8c6iy8rlxm8w9vqw7gb7s1ljadrn049fmf70cyh42vdfhrf";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    sha256 = "03kickal0iiby82wa5flar18kyv82s9s6d4xhk5h4bi5kfcyfjzl";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    sha256 = "1cqh1sv3h5j7ixyb7axxbdkqx6cxy00p4np4j91kpm492rf4s25b";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    sha256 = "0bh5bi25nk9w9xi8z23ws45q5yia6k7dg3i4axhfqlnj145l011x";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    sha256 = "0c3g3g3jmhlhw4klrc86ka9fjbl7i59ds1fadsb2l8nqf8z3kb19";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    sha256 = "0aqqi1v4wx51h51mk956y783wzags13wa7mgqyclacmsmpv02ps3";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding.Extensions";
    version = "4.3.0";
    sha256 = "0lqhgqi0i8194ryqq6v2gqx0fb86db2gqknbm0aq31wb378j7ip8";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    sha256 = "03mnvkhskbzxddz4hm113zsch1jyzh2cs450dk3rgfjp8crlw1va";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Timer";
    version = "4.3.0";
    sha256 = "0aw4phrhwqz9m61r79vyfl5la64bjxj8l34qnrcwb28v49fg2086";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "16rnxzpk5dpbbl1x354yrlsbvwylrq456xzpsha1n9y3glnhyx9d";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "0rwpqngkqiapqc5c2cpkj7idhngrgss5qpnqg0yh40mbyflcxf8i";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "0hkg03sgm2wyq8nqk6dbm9jh5vcq57ry42lkqdmfklrw89lsmr59";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "1n06gxwlinhs0w7s8a94r1q3lwqzvynxwd3mp10ws9bg6gck8n4r";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "0c2p354hjx58xhhz7wv6div8xpi90sc6ibdm40qin21bvi7ymcaa";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "0404wqrc7f2yc0wxv71y3nnybvqx8v4j9d47hlscxy759a525mc3";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.0.0";
    sha256 = "1ppk69xk59ggacj9n7g6fyxvzmk1g5p4fkijm0d7xqfkig98qrkf";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    sha256 = "15hgf6zaq9b8br2wi1i3x0zvmk410nlmsmva9p0bbg73v6hml5k4";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Compression";
    version = "4.1.0";
    sha256 = "0d720z4lzyfcabmmnvh0bnj76ll7djhji2hmfh3h44sdkjnlkknk";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Compression";
    version = "4.3.0";
    sha256 = "1vvivbqsk6y4hzcid27pqpm5bsi6sc50hvqwbcx8aap5ifrxfs8d";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.0.1";
    sha256 = "1hgv2bmbaskx77v8glh7waxws973jn4ah35zysnkxmf0196sfxg6";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.3.0";
    sha256 = "1n6rgz5132lcibbch1qlf0g9jk60r0kqv087hxc0lisy50zpm7kk";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Security";
    version = "4.0.1";
    sha256 = "1nk4pf8vbrgf73p0skhwmzhgz1hax3j123ilhwdncr47l3x1dbhk";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography";
    version = "4.0.0";
    sha256 = "0k57aa2c3b10wl3hfqbgrl7xq7g8hh3a3ir44b31dn5p61iiw3z9";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    sha256 = "1b61p6gw1m02cc1ry996fl49liiwky6181dzr873g9ds92zl326q";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "18pzfdlwsg2nb1jjjjzyb5qlgy6xjxzmhnfaijq5s2jw3cm3ab97";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "0zy5r25jppz48i2bkg8b9lfig24xixg6nm3xyr1379zdnqnpm8f6";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "0qyynf9nz5i7pc26cwhgi8j62ps27sqmf78ijcfgzab50z9g8ay3";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "096ch4n4s8k82xga80lfmpimpzahd2ip1mgwdqgar0ywbbl6x438";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "1klrs545awhayryma6l7g2pvnp9xy4z0r1i40r80zb45q3i9nbyf";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "1dm8fifl7rf1gy7lnwln78ch4rw54g0pl5g1c189vawavll7p6rj";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    sha256 = "10yc8jdrwgcl44b4g93f1ds76b176bajd3zqi2faf5rvh1vy9smi";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "0zcxjv5pckplvkg0r6mw3asggm7aqzbdjimhvsasb0cgm59x09l3";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "1m9z1k9kzva9n9kwinqxl97x2vgl79qhqjlv17k9s2ymcyv2bwr6";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "0vhynn79ih7hw7cwjazn87rm9z9fj0rvxgzlab36jybgcpcgphsn";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "1cpx56mcfxz7cpn57wvj18sjisvzq8b5vd9rw16ihd2i6mcp3wa1";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "160p68l2c7cqmyqjwxydcvgw7lvl1cr0znkw8fp24d1by9mqc8p3";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "15gsm1a8jdmgmf8j5v1slfz8ks124nfdhk2vxs2rw3asrxalg8hi";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "15zrc8fgd8zx28hdghcj5f5i34wf3l6bq5177075m2bc2j34jrqy";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "0q0n5q1r1wnqmr5i5idsrd9ywl33k0js4pngkwq9p368mbxp8x1w";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "1p4dgxax6p7rlgj4q73k73rslcnz4wdcv8q2flg1s8ygwcm58ld5";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.2";
    sha256 = "1x0g58pbpjrmj2x2qw17rdwwnrcl0wvim2hdwz48lixvwvp22n9c";
  })
  (fetchNuGet {
    pname = "runtime.unix.Microsoft.Win32.Primitives";
    version = "4.3.0";
    sha256 = "0y61k9zbxhdi0glg154v30kkq7f8646nif8lnnxbvkjpakggd5id";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Console";
    version = "4.3.0";
    sha256 = "1pfpkvc6x2if8zbdzg9rnc5fx51yllprl8zkm5npni2k50lisy80";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    sha256 = "1lps7fbnw34bnh3lm31gs5c0g0dh7548wfmb8zz62v0zqz71msj5";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.IO.FileSystem";
    version = "4.3.0";
    sha256 = "14nbkhvs7sji5r1saj2x8daz82rnf9kx28d3v2qss34qbr32dzix";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Primitives";
    version = "4.3.0";
    sha256 = "0bdnglg59pzx9394sy4ic66kmxhqp8q8bvmykdxcbs5mm0ipwwm4";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Sockets";
    version = "4.3.0";
    sha256 = "03npdxzy8gfv035bv1b9rz7c7hv0rxl5904wjz51if491mw0xy12";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    sha256 = "1jx02q6kiwlvfksq1q9qr17fj78y5v6mwsszav4qcz9z25d5g6vk";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    sha256 = "0pnxxmm8whx38dp6yvwgmh22smknxmqs5n513fc7m4wxvs1bvi4p";
  })
  (fetchNuGet {
    pname = "SCrypt";
    version = "2.0.0.2";
    sha256 = "03ira8iv45zcsv613bic0ak31v9am13x29dsj3j17xzhx65rg926";
  })
  (fetchNuGet {
    pname = "Seq.Api";
    version = "2023.1.0";
    sha256 = "1liwvn83hzqdpayigrir0y49l31d7sncnbxmz2m8m66r3ksdk8k1";
  })
  (fetchNuGet {
    pname = "Shouldly";
    version = "4.1.0";
    sha256 = "1mgw1nack5781qqq3kfw972bzp8xpsrlyb74k94yqcwpkfqn9iva";
  })
  (fetchNuGet {
    pname = "Snappy.Standard";
    version = "0.2.0";
    sha256 = "1dbrp35r1k6gdpqx576kcrplxbdxs32223pl4ds9hwhpf1fjac65";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.bundle_e_sqlite3";
    version = "2.0.6";
    sha256 = "1ip0a653dx5cqybxg27zyz5ps31f2yz50g3jvz3vx39isx79gax3";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "1.1.5";
    sha256 = "1944ni5nzazhr5n4g2md9q1prr9hx2nvifhgfpvn1cp1r2iy52nj";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.core";
    version = "2.0.6";
    sha256 = "1w4iyg0v1v1z2m7akq7rv8lsgixp2m08732vr14vgpqs918bsy1i";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.lib.e_sqlite3";
    version = "2.0.6";
    sha256 = "16378rh1lcqxynf5qj0kh8mrsb0jp37qqwg4285kqc5pknvh1bx3";
  })
  (fetchNuGet {
    pname = "SQLitePCLRaw.provider.e_sqlite3";
    version = "2.0.6";
    sha256 = "0chgrqyycb1kqnaxnhhfg0850b94blhzni8zn79c7ggb3pd2ykyz";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.1.0";
    sha256 = "0fv3cma1jp4vgj7a8hqc9n7hr1f1kjp541s6z0q1r6nazb4iz9mz";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.3.0";
    sha256 = "1649qvy3dar900z3g817h17nl8jp4ka5vcfmsr05kh0fshn7j3ya";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.0.0";
    sha256 = "13s659bcmg9nwb6z78971z1lr6bmh2wghxi1ayqyzl4jijd351gr";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.3.0";
    sha256 = "0fgns20ispwrfqll4q1zc1waqcmylb3zc50ys9x8zlwxh9pmd9jy";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.0";
    sha256 = "1ywfqn4md6g3iilpxjn5dsr0f5lx6z0yvhqp4pgjcamygg73cz2c";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    sha256 = "04kb1mdrlcixj9zh1xdi5as0k0qi8byr5mi3p3jcxx72qz93s2y3";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "5.0.0";
    sha256 = "14zs2wqkmdlxzj8ikx19n321lsbarx5vl2a8wrachymxn8zb5njh";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.0.11";
    sha256 = "1ga40f5lrwldiyw6vy67d0sg7jd7ww6kgwbksm19wrvq9hr0bsm6";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    sha256 = "19r4y64dqyrq6k4706dnyhhw7fs24kpp3awak7whzss39dakpxk9";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.0.12";
    sha256 = "07y08kvrzpak873pmyxs129g1ch8l27zmg51pcyj2jvq03n0r0fc";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.3.0";
    sha256 = "0wi10md9aq33jrkh2c24wr2n9hrpyamsdhsxdcnf43b7y86kkii8";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.2.0";
    sha256 = "1jm4pc666yiy7af1mcf7766v710gp0h40p228ghj6bavx7xfa38m";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.5.0";
    sha256 = "1d5gjn5afnrf461jlxzawcvihz195gayqpcfbv6dd7pxa9ialn06";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "6.0.0";
    sha256 = "1js98kmjn47ivcvkjqdmyipzknb9xbndssczm8gq224pbaj1p88c";
  })
  (fetchNuGet {
    pname = "System.Collections.NonGeneric";
    version = "4.3.0";
    sha256 = "07q3k0hf3mrcjzwj8fwk6gv3n51cb513w4mgkfxzm3i37sc9kz7k";
  })
  (fetchNuGet {
    pname = "System.Collections.Specialized";
    version = "4.3.0";
    sha256 = "1sdwkma4f6j85m3dpb53v9vcgd0zyc9jb33f8g63byvijcj39n20";
  })
  (fetchNuGet {
    pname = "System.ComponentModel";
    version = "4.0.1";
    sha256 = "0v4qpmqlzyfad2kswxxj2frnaqqhz9201c3yn8fmmarx5vlzg52z";
  })
  (fetchNuGet {
    pname = "System.ComponentModel";
    version = "4.3.0";
    sha256 = "0986b10ww3nshy30x9sjyzm0jx339dkjxjj3401r3q0f6fx2wkcb";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "4.1.0";
    sha256 = "0l6m3z6h2qjjam1rp1fzk7zz5czjjazmw78rbh72x25y6kmyn6wf";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "4.5.0";
    sha256 = "1jj6f6g87k0iwsgmg3xmnn67a14mq88np0l1ys5zkxhkvbc8976p";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Primitives";
    version = "4.3.0";
    sha256 = "1svfmcmgs0w0z9xdw2f2ps05rdxmkxxhf0l17xk9l1l8xfahkqr0";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.TypeConverter";
    version = "4.3.0";
    sha256 = "17ng0p7v3nbrg3kycz10aqrrlw4lz9hzhws09pfh8gkwicyy481x";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "4.4.0";
    sha256 = "1hjgmz47v5229cbzd2pwz2h0dkq78lb2wp9grx8qr72pb5i0dk7v";
  })
  (fetchNuGet {
    pname = "System.Configuration.ConfigurationManager";
    version = "7.0.0";
    sha256 = "149d9kmakzkbw69cip1ny0wjlgcvnhrr7vz5pavpsip36k2mw02a";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.0.0";
    sha256 = "0ynxqbc3z1nwbrc11hkkpw9skw116z4y9wjzn7id49p9yi7mzmlf";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.3.0";
    sha256 = "1flr7a9x920mr5cjsqmsy9wgnv3lvd0h1g521pdr1lkb2qycy7ay";
  })
  (fetchNuGet {
    pname = "System.Data.Common";
    version = "4.3.0";
    sha256 = "12cl7vy3him9lmal10cyxifasf75x4h5b239wawpx3vzgim23xq3";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.0.11";
    sha256 = "0gmjghrqmlgzxivd2xl50ncbglb7ljzb66rlx8ws6dv8jm0d5siz";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    sha256 = "00yjlf19wjydyr6cfviaph3vsjzg3d5nvnya26i2fvfg53sknh3y";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.0.0";
    sha256 = "1n6c3fbz7v8d3pn77h4v5wvsfrfg7v1c57lg3nff3cjyh597v23m";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.3.0";
    sha256 = "0z6m3pbiy0qw6rn3n209rrzf9x1k4002zh90vwcrsym09ipm2liq";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "6.0.0";
    sha256 = "0rrihs9lnb1h6x4h0hn6kgfnh58qq7hx8qq99gh6fayx4dcnx3s5";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "6.0.0";
    sha256 = "08y1x2d5w2hnhkh9r1998pjc7r4qp0rmzax062abha85s11chifd";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "7.0.0";
    sha256 = "16p8z975dnzmncfifa9gw9n3k9ycpr2qvz7lglpghsvx0fava8k9";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.FileVersionInfo";
    version = "4.0.0";
    sha256 = "1s5vxhy7i09bmw51kxqaiz9zaj9am8wsjyz13j85sp23z267hbv3";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Process";
    version = "4.1.0";
    sha256 = "061lrcs7xribrmq7kab908lww6kn2xn1w3rdc41q189y0jibl19s";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.StackTrace";
    version = "4.0.1";
    sha256 = "0q29axqklpl36vvyni5h1cyb02lfvvkqprb9wfvcdca3181q5al2";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.0.1";
    sha256 = "19cknvg07yhakcvpxg3cxa0bwadplin6kyxd8mpjjpwnp56nl85x";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.3.0";
    sha256 = "0in3pic3s2ddyibi8cvgl102zmvp9r9mchh82ns9f0ms4basylw1";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.1.0";
    sha256 = "1d2r76v1x610x61ahfpigda89gd13qydz6vbwzhpqlyvq8jj6394";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.3.0";
    sha256 = "1m3bx6c2s958qligl67q7grkwfz3w53hpy7nc97mh6f7j5k168c4";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "7.0.0";
    sha256 = "0jwyv5zjxzr4bm4vhmz394gsxqa02q6pxdqd2hwy1f116f0l30dp";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.0.11";
    sha256 = "1pla2dx8gkidf7xkciig6nifdsb494axjvzvann8g2lp3dbqasm9";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.3.0";
    sha256 = "1d951hrvrpndk7insiag80qxjbf2y0y39y8h5hnq9612ws661glk";
  })
  (fetchNuGet {
    pname = "System.Formats.Asn1";
    version = "7.0.0";
    sha256 = "1a14kgpqz4k7jhi7bs2gpgf67ym5wpj99203zxgwjypj7x47xhbq";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.0.11";
    sha256 = "070c5jbas2v7smm660zaf1gh0489xanjqymkvafcs4f8cdrs1d5d";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    sha256 = "1cp68vv683n6ic2zqh2s1fn4c2sd87g5hpp6l4d4nj4536jz98ki";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.0.1";
    sha256 = "0bv0alrm2ck2zk3rz25lfyk9h42f3ywq77mx1syl6vvyncnpg4qh";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.3.0";
    sha256 = "1xwl230bkakzzkrggy1l1lxmm3xlhk4bq2pkv790j5lm8g887lxq";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.0.1";
    sha256 = "0hjhdb5ri8z9l93bw04s7ynwrjrhx2n0p34sf33a9hl9phz69fyc";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.3.0";
    sha256 = "02a5zfxavhv3jd437bsncbhd2fp1zv4gxzakp1an9l6kdq1mcqls";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "5.6.0";
    sha256 = "146avzhn87ik22zww3dcs0a5qdk8kzcwzv4qby8g9h6blh3sp72h";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "6.27.0";
    sha256 = "0fihix48dk0jrkawby62fs163dv5hsh63vdhdyp7hfz6nabsqs2j";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.1.0";
    sha256 = "1g0yb8p11vfd0kbkyzlfsbsp5z44lwsvyc0h3dpw6vqnbi035ajp";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    sha256 = "05l9qdrzhm4s5dixmx68kxwif4l99ll5gqmh7rqgw554fx0agv5f";
  })
  (fetchNuGet {
    pname = "System.IO.Compression";
    version = "4.1.0";
    sha256 = "0iym7s3jkl8n0vzm3jd6xqg9zjjjqni05x45dwxyjr2dy88hlgji";
  })
  (fetchNuGet {
    pname = "System.IO.Compression";
    version = "4.3.0";
    sha256 = "084zc82yi6yllgda0zkgl2ys48sypiswbiwrv7irb3r0ai1fp4vz";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.0.1";
    sha256 = "0h72znbagmgvswzr46mihn7xm7chfk2fhrp5krzkjf29pz0i6z82";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.3.0";
    sha256 = "1yxy5pq4dnsm9hlkg9ysh5f6bf3fahqqb6p8668ndy5c0lk7w2ar";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.0.1";
    sha256 = "0kgfpw6w4djqra3w5crrg8xivbanh1w9dh3qapb28q060wb9flp1";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.3.0";
    sha256 = "0z2dfrbra9i6y16mm9v1v6k47f0fm617vlb7s5iybjjsz6g1ilmw";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.0.1";
    sha256 = "1s0mniajj3lvbyf7vfb5shp4ink5yibsx945k6lvxa96r8la1612";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.3.0";
    sha256 = "0j6ndgglcf4brg2lz4wzsh1av1gh8xrzdsn9f0yznskhqn1xzj9c";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Watcher";
    version = "4.0.0";
    sha256 = "0rgfjiqz8dqy8hmbfsls4sa46ss6p9vh86cvn1vqx7zg45pf3hir";
  })
  (fetchNuGet {
    pname = "System.IO.MemoryMappedFiles";
    version = "4.0.0";
    sha256 = "1ahp27llf76ngc0fngl8zy4y1sgflzrkmxddilnd0l0cbbq1lm6m";
  })
  (fetchNuGet {
    pname = "System.IO.UnmanagedMemoryStream";
    version = "4.0.1";
    sha256 = "012g8nwbfv94rhblsb3pxn1bazfpgjiy3kmy00679gg3651b87jb";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.1.0";
    sha256 = "1ppg83svb39hj4hpp5k7kcryzrf3sfnm08vxd5sm2drrijsla2k5";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    sha256 = "1w0gmba695rbr80l1k2h4mrwzbzsyfl2z4klmpbsvsg5pm4a56s7";
  })
  (fetchNuGet {
    pname = "System.Linq.Async";
    version = "6.0.1";
    sha256 = "10ira8hmv0i54yp9ggrrdm1c06j538sijfjpn1kmnh9j2xk5yzmq";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.1.0";
    sha256 = "1gpdxl6ip06cnab7n3zlcg6mqp7kknf73s8wjinzi4p0apw82fpg";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.3.0";
    sha256 = "0ky2nrcvh70rqq88m9a5yqabsl4fyd17bpr63iy2mbivjs2nyypv";
  })
  (fetchNuGet {
    pname = "System.Linq.Parallel";
    version = "4.0.1";
    sha256 = "0i33x9f4h3yq26yvv6xnq4b0v51rl5z8v1bm7vk972h5lvf4apad";
  })
  (fetchNuGet {
    pname = "System.Linq.Queryable";
    version = "4.0.1";
    sha256 = "11jn9k34g245yyf260gr3ldzvaqa9477w2c5nhb1p8vjx4xm3qaw";
  })
  (fetchNuGet {
    pname = "System.Management";
    version = "5.0.0";
    sha256 = "09hyv3p0zd549577clydlb2szl84m4gvdjnsry73n8b12ja7d75s";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.0";
    sha256 = "1layqpcx1q4l805fdnj2dfqp6ncx2z42ca06rgsr6ikq4jjgbv30";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.1";
    sha256 = "0f07d7hny38lq9w69wx4lxkn4wszrqf9m9js6fh9is645csm167c";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    sha256 = "0naqahm3wljxb5a911d37mwjqjdxv9l0b49p5dmfyijvni2ppy8a";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.4";
    sha256 = "14gbbs22mcxwggn0fcfs1b062521azb9fbb7c113x0mq6dzq9h6y";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.1.0";
    sha256 = "1i5rqij1icg05j8rrkw4gd4pgia1978mqhjzhsjg69lvwcdfg8yb";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.3.0";
    sha256 = "1i4gc757xqrzflbk7kc5ksn20kwwfjhw9w7pgdkn19y3cgnl302j";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.3.4";
    sha256 = "0kdp31b8819v88l719j6my0yas6myv9d1viql3qz5577mv819jhl";
  })
  (fetchNuGet {
    pname = "System.Net.NameResolution";
    version = "4.0.0";
    sha256 = "0dj3pvpv069nyia28gkl4a0fb7q33hbxz2dg25qvpah3l7pbl0qh";
  })
  (fetchNuGet {
    pname = "System.Net.NameResolution";
    version = "4.3.0";
    sha256 = "15r75pwc0rm3vvwsn8rvm2krf929mjfwliv0mpicjnii24470rkq";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.0.11";
    sha256 = "10xzzaynkzkakp7jai1ik3r805zrqjxiz7vcagchyxs2v26a516r";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.3.0";
    sha256 = "0c87k50rmdgmxx7df2khd9qj7q35j9rzdmm2572cc55dygmdk3ii";
  })
  (fetchNuGet {
    pname = "System.Net.Requests";
    version = "4.0.11";
    sha256 = "13mka55sa6dg6nw4zdrih44gnp8hnj5azynz47ljsh2791lz3d9h";
  })
  (fetchNuGet {
    pname = "System.Net.Security";
    version = "4.0.0";
    sha256 = "0ybyfssnm0cri37byhxnkfrzprz77nizbfj553x7s1vry2pnm5gb";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.1.0";
    sha256 = "1385fvh8h29da5hh58jm1v78fzi9fi5vj93vhlm2kvqpfahvpqls";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.3.0";
    sha256 = "1ssa65k6chcgi6mfmzrznvqaxk8jp0gvl77xhf1hbzakjnpxspla";
  })
  (fetchNuGet {
    pname = "System.Net.WebHeaderCollection";
    version = "4.0.1";
    sha256 = "10bxpxj80c4z00z3ksrfswspq9qqsw8jwxcbzvymzycb97m9b55q";
  })
  (fetchNuGet {
    pname = "System.Net.WebSockets.WebSocketProtocol";
    version = "4.5.3";
    sha256 = "0z9ccndkkq6gpsh35q3pjm4zya47p6vakcyj8nc352g4wiizqc8c";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.1.1";
    sha256 = "1xkzrpl700pp0l6dc9fx7cj318i596w0i0qixsbrz5v65fnhbzia";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.0.12";
    sha256 = "1sybkfi60a4588xn34nd9a58png36i0xr4y4v4kqpg8wlvy5krrj";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.3.0";
    sha256 = "191p63zy5rpqx7dnrb3h7prvgixmk168fhvvkkvhlazncf8r3nc2";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    sha256 = "04r1lkdnsznin0fj4ya1zikxiqr0h6r6a1ww2dsm60gqhdrf0mvx";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "4.3.2";
    sha256 = "1ibfp7g9sy32rx08dlz9kqgs5a3c22y40nm5sb4f66i5yd3v3sks";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.1.0";
    sha256 = "1js89429pfw79mxvbzp8p3q93il6rdff332hddhzi5wqglc4gml9";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    sha256 = "0xl55k0mw8cd8ra6dxzh974nxif58s3k1rjv1vbd7gjbjr39j11m";
  })
  (fetchNuGet {
    pname = "System.Reflection.DispatchProxy";
    version = "4.0.1";
    sha256 = "1maglcnvm3h8bfmx3rvwg4wjda7527iqp38cg1r6vh9japrw1n0r";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.0.1";
    sha256 = "0ydqcsvh6smi41gyaakglnv252625hf29f7kywy2c70nhii2ylqp";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.3.0";
    sha256 = "11f8y3qfysfcrscjpjym9msk7lsfxkk4fmz9qq95kn3jd0769f74";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.7.0";
    sha256 = "121l1z2ypwg02yz84dy6gr82phpys0njk7yask3sihgy214w43qp";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.0.1";
    sha256 = "1pcd2ig6bg144y10w7yxgc9d22r7c7ww7qn1frdfwgxr24j9wvv0";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.3.0";
    sha256 = "0w1n67glpv8241vnpz1kl14sy7zlnw414aqwj4hcx5nd86f6994q";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.0.1";
    sha256 = "1s4b043zdbx9k39lfhvsk68msv1nxbidhkq6nbm27q7sf8xcsnxr";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.3.0";
    sha256 = "0ql7lcakycrvzgi9kxz1b3lljd990az1x6c4jsiwcacrvimpib5c";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.0.1";
    sha256 = "0m7wqwq0zqq9gbpiqvgk3sr92cbrw7cp3xn53xvw7zj6rz6fdirn";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    sha256 = "02bly8bdc98gs22lqsfx9xicblszr2yan7v2mmw3g7hy6miq5hwq";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.3.0";
    sha256 = "1y5m6kryhjpqqm2g3h3b6bzig13wkiw954x3b7icqjm6xypm1x3b";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    sha256 = "1wdbavrrkajy7qbdblpbpbalbdl48q3h34cchz24gvdgyrlf15r4";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.0.1";
    sha256 = "1bangaabhsl4k9fg8khn83wm6yial8ik1sza7401621jc6jrym28";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    sha256 = "04xqa33bld78yv5r93a8n76shvc8wwcdgr1qvvjh959g3rc31276";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.1.0";
    sha256 = "1bjli8a7sc7jlxqgcagl9nh8axzfl11f4ld3rjqsyxc516iijij7";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.3.0";
    sha256 = "0y2ssg08d817p0vdag98vn238gyrrynjdj4181hdg780sif3ykp1";
  })
  (fetchNuGet {
    pname = "System.Resources.Reader";
    version = "4.0.0";
    sha256 = "1jafi73dcf1lalrir46manq3iy6xnxk2z7gpdpwg4wqql7dv3ril";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.0.1";
    sha256 = "0b4i7mncaf8cnai85jv3wnw6hps140cxz8vylv2bik6wyzgvz7bi";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    sha256 = "0sjqlzsryb0mg4y4xzf35xi523s4is4hz9q4qgdvlvgivl7qxn49";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.1.0";
    sha256 = "02hdkgk13rvsd6r9yafbwzss8kr55wnj8d5c7xjnp8gqrwc8sn0m";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    sha256 = "066ixvgbf2c929kgknshcxqj6539ax7b9m570cp8n179cpfkapz7";
  })
  (fetchNuGet {
    pname = "System.Runtime.Caching";
    version = "7.0.0";
    sha256 = "12k47lvi12x9idn18bq2hls2zcwx9qfag05scbm0ji5akzplwlyq";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.0";
    sha256 = "17labczwqk3jng3kkky73m0jhi8wc21vbl7cz5c0hj2p1dswin43";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.1";
    sha256 = "1xcrjx5fwg284qdnxyi2d0lzdm5q4frlpkp0nf6vvkx1kdz2prrf";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "5.0.0";
    sha256 = "02k25ivn50dmqx5jn8hawwmz24yf0454fjd823qk6lygj9513q4x";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.1.0";
    sha256 = "0rw4rm4vsm3h3szxp9iijc3ksyviwsv6f63dng3vhqyg4vjdkc2z";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    sha256 = "1ykp3dnhwvm48nap8q23893hagf665k0kn3cbgsqpwzbijdcgc60";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.0.1";
    sha256 = "1g0zrdi5508v49pfm3iii2hn6nm00bgvfpjq1zxknfjrxxa20r4g";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    sha256 = "0sw2gfj2xr7sw9qjn0j3l9yw07x73lcs97p8xfc9w1x9h5g5m7i8";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.1.0";
    sha256 = "01kxqppx3dr3b6b286xafqilv4s2n0gqvfgzfd4z943ga9i81is1";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    sha256 = "00hywrn4g7hva1b2qri2s6rabzwgxnbpw9zfxmz28z09cpwwgh7j";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.0.0";
    sha256 = "0glmvarf3jz5xh22iy3w9v3wyragcm4hfdr17v90vs7vcrm7fgp6";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.3.0";
    sha256 = "0q18r1sh4vn7bvqgd6dmqlw5v28flbpj349mkdish2vjyvmnb2ii";
  })
  (fetchNuGet {
    pname = "System.Runtime.Loader";
    version = "4.0.0";
    sha256 = "0lpfi3psqcp6zxsjk2qyahal7zaawviimc8lhrlswhip2mx7ykl0";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.0.1";
    sha256 = "1y308zfvy0l5nrn46mqqr4wb4z1xk758pkk8svbz8b5ij7jnv4nn";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.3.0";
    sha256 = "19rav39sr5dky7afygh309qamqqmi9kcwvz3i0c5700v0c5cg61z";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    sha256 = "17n3lrrl6vahkqmhlpn3w20afgz09n7i6rv0r3qypngwi7wqdr5r";
  })
  (fetchNuGet {
    pname = "System.Security.Claims";
    version = "4.0.1";
    sha256 = "03dw0ls49bvsrffgwycyifjgz0qzr9r85skqhdyhfd51fqf398n6";
  })
  (fetchNuGet {
    pname = "System.Security.Claims";
    version = "4.3.0";
    sha256 = "0jvfn7j22l3mm28qjy3rcw287y9h65ha4m940waaxah07jnbzrhn";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.2.0";
    sha256 = "148s9g5dgm33ri7dnh19s4lgnlxbpwvrw2jnzllq2kijj4i4vs85";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.3.0";
    sha256 = "03sq183pfl5kp7gkvq77myv7kbpdnq3y0xj7vi4q1kaw54sny0ml";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.2.0";
    sha256 = "118jijz446kix20blxip0f0q8mhsh9bz118mwc2ch1p6g7facpzc";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.3.0";
    sha256 = "1k468aswafdgf56ab6yrn7649kfqx2wm9aslywjam1hdmk5yypmv";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.5.0";
    sha256 = "1pm4ykbcz48f1hdmwpia432ha6qbb9kbrxrrp7cg3m8q8xn52ngn";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.0.0";
    sha256 = "1cwv8lqj8r15q81d2pz2jwzzbaji0l28xfrpw29kdpsaypm92z2q";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.3.0";
    sha256 = "1x5wcrddf2s3hb8j78cry7yalca4lb5vfnkrysagbn6r9x6xvrx1";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.0.0";
    sha256 = "0a8y1a5wkmpawc787gfmnrnbzdgxmx1a14ax43jf3rj9gxmy3vk4";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.3.0";
    sha256 = "1jr6w70igqn07k5zs1ph6xja97hxnb3mqbspdrff6cvssgrixs32";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.0.0";
    sha256 = "16sx3cig3d0ilvzl8xxgffmxbiqx87zdi8fc73i3i7zjih1a7f4q";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    sha256 = "0givpvvj8yc7gv4lhb6s1prq6p2c4147204a0wib89inqzd87gqc";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Pkcs";
    version = "7.0.0";
    sha256 = "0834gh4k84xbv73mk6s9djkksq3bd6m2k1ixincjnaawv0pyz7fw";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.0.0";
    sha256 = "0i7cfnwph9a10bm26m538h5xcr8b36jscp9sy1zhgifksxz4yixh";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.3.0";
    sha256 = "0pyzncsv48zwly3lw4f2dayqswcfvdwq2nz0dgwmi7fj3pn64wby";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "4.4.0";
    sha256 = "1q8ljvqhasyynp94a1d7jknk946m20lkwy2c3wa8zw2pc517fbj6";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "7.0.0";
    sha256 = "15s9s6hsj9bz0nzw41mxbqdjgjd71w2djqbv0aj413gfi9amybk9";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.ProtectedData";
    version = "7.0.1";
    sha256 = "1nq9ngkqha70rv41692c79zq09cx6m85wkp3xj9yc31s62afyl5i";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.1.0";
    sha256 = "0clg1bv55mfv5dq00m19cp634zx6inm31kf8ppbq1jgyjf2185dh";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.3.0";
    sha256 = "0valjcz5wksbvijylxijjxb1mp38mdhv03r533vnx1q3ikzdav9h";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Xml";
    version = "7.0.1";
    sha256 = "0p6kx6ag0il7rxxcvm84w141phvr7fafjzxybf920bxwa0jkwzq8";
  })
  (fetchNuGet {
    pname = "System.Security.Permissions";
    version = "7.0.0";
    sha256 = "0wkm6bj4abknzj41ygkziifx8mzhj4bix92wjvj6lihaw1gniq8c";
  })
  (fetchNuGet {
    pname = "System.Security.Principal";
    version = "4.0.1";
    sha256 = "1nbzdfqvzzbgsfdd5qsh94d7dbg2v4sw0yx6himyn52zf8z6007p";
  })
  (fetchNuGet {
    pname = "System.Security.Principal";
    version = "4.3.0";
    sha256 = "12cm2zws06z4lfc4dn31iqv7072zyi4m910d4r6wm8yx85arsfxf";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.0.0";
    sha256 = "1d3vc8i0zss9z8p4qprls4gbh7q4218l9845kclx7wvw41809k6z";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.3.0";
    sha256 = "00a0a7c40i3v4cb20s2cmh9csb5jv2l0frvnlzyfxh848xalpdwr";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    sha256 = "1mpk7xj76lxgz97a5yg93wi8lj0l8p157a5d50mmjy3gbz1904q8";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.0.11";
    sha256 = "1dyqv0hijg265dwxg6l7aiv74102d6xjiwplh2ar1ly6xfaa4iiw";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    sha256 = "1f04lkir4iladpp51sdgmis9dj4y8v08cka0mbmsy0frc9a4gjqr";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "4.0.1";
    sha256 = "00wpm3b9y0k996rm9whxprngm8l500ajmzgy2ip9pgwk0icp06y3";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.0.11";
    sha256 = "08nsfrpiwsg9x5ml4xyl3zyvjfdi4mvbqf93kjdh11j4fwkznizs";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.3.0";
    sha256 = "11q1y8hh5hrp5a3kw25cb6l00v5l5dvirkz8jr3sq00h1xgcgrxy";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "4.5.0";
    sha256 = "0srd5bva52n92i90wd88pzrqjsxnfgka3ilybwh7s6sf469y5s53";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "4.7.2";
    sha256 = "0ap286ykazrl42if59bxhzv81safdfrrmfqr3112siwyajx4wih9";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    sha256 = "06n9ql3fmhpjl32g3492sj181zjml5dlcc5l76xq2h38c4f87sai";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "7.0.0";
    sha256 = "1151hbyrcf8kyg1jz8k9awpbic98lwz9x129rg7zk1wrs6vjlpxl";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "4.7.2";
    sha256 = "10xj1pw2dgd42anikvj9qm23ccssrcp7dpznpj4j7xjp1ikhy3y4";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.0";
    sha256 = "1si2my1g0q0qv1hiqnji4xh9wd05qavxnzj9dwgs23iqvgjky0gl";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.5";
    sha256 = "12fg196sdq3gcjcz365kypfkkmdrprpcw2fvjnww9jqa4yn8v99l";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "7.0.0";
    sha256 = "0scb0lp7wbgcinaa4kqiqs7b8i5nx4ppfad81138jiwd1sl37pyp";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.1.0";
    sha256 = "1mw7vfkkyd04yn2fbhm38msk7dz2xwvib14ygjsb8dq2lcvr18y7";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.3.0";
    sha256 = "1bgq51k7fwld0njylfn7qc5fmwrk2137gdq7djqdsw347paa9c2l";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.0.11";
    sha256 = "19x946h926bzvbsgj28csn46gak2crv2skpwsx80hbgazmkgb1ls";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    sha256 = "0rw9wfamvhayp5zh3j7p1yfmx9b5khbf4q50d8k5rk993rskfd34";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "4.7.0";
    sha256 = "1cb9arib2xzf8kc8nzgla8lyhs8qzddjx5n4hwbp5vrm81ihhsi1";
  })
  (fetchNuGet {
    pname = "System.Threading.Overlapped";
    version = "4.0.1";
    sha256 = "0fi79az3vmqdp9mv3wh2phblfjls89zlj6p9nc3i9f6wmfarj188";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.0.11";
    sha256 = "0nr1r41rak82qfa5m0lhk9mp0k93bvfd7bbd9sdzwx9mb36g28p5";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    sha256 = "134z3v9abw3a6jsw17xl3f6hqjpak5l682k2vz39spj4kmydg6k7";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "4.6.0";
    sha256 = "0a1davr71wssyn4z1hr75lk82wqa0daz0vfwkmg1fm3kckfd72k1";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.0.0";
    sha256 = "1cb51z062mvc2i8blpzmpn9d9mm4y307xrwi65di8ri18cz5r1zr";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.3.0";
    sha256 = "1xxcx2xh8jin360yjwm4x4cf5y3a2bwpn2ygkfkwkicz7zk50s2z";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Parallel";
    version = "4.0.1";
    sha256 = "114wdg32hr46dfsnns3pgs67kcha5jn47p5gg0mhxfn5vrkr2p75";
  })
  (fetchNuGet {
    pname = "System.Threading.Thread";
    version = "4.0.0";
    sha256 = "1gxxm5fl36pjjpnx1k688dcw8m9l7nmf802nxis6swdaw8k54jzc";
  })
  (fetchNuGet {
    pname = "System.Threading.ThreadPool";
    version = "4.0.10";
    sha256 = "0fdr61yjcxh5imvyf93n2m3n5g9pp54bnw2l1d2rdl9z6dd31ypx";
  })
  (fetchNuGet {
    pname = "System.Threading.ThreadPool";
    version = "4.3.0";
    sha256 = "027s1f4sbx0y1xqw2irqn6x161lzj8qwvnh2gn78ciiczdv10vf1";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.0.1";
    sha256 = "15n54f1f8nn3mjcjrlzdg6q3520571y012mx7v991x2fvp73lmg6";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.3.0";
    sha256 = "1nx773nsx6z5whv8kaa1wjh037id2f1cxhb69pvgv12hd2b6qs56";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.3.0";
    sha256 = "1227k7fxbxapq7dms4lvwwjdf3pr1jcsmhy2nzzhj6g6hs530hxn";
  })
  (fetchNuGet {
    pname = "System.Windows.Extensions";
    version = "7.0.0";
    sha256 = "11r9f0v7qp365bdpq5ax023yra4qvygljz18dlqs650d44iay669";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.0.11";
    sha256 = "0c6ky1jk5ada9m94wcadih98l6k1fvf6vi7vhn1msjixaha419l5";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.3.0";
    sha256 = "0c47yllxifzmh8gq6rq6l36zzvw4kjvlszkqa9wq3fr59n0hl3s1";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.0.11";
    sha256 = "0n4lvpqzy9kc7qy1a4acwwd7b7pnvygv895az5640idl2y9zbz18";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.3.0";
    sha256 = "08h8fm4l77n0nd4i4fk2386y809bfbwqb7ih9d7564ifcxr5ssxd";
  })
  (fetchNuGet {
    pname = "System.Xml.XmlDocument";
    version = "4.0.1";
    sha256 = "0ihsnkvyc76r4dcky7v3ansnbyqjzkbyyia0ir5zvqirzan0bnl1";
  })
  (fetchNuGet {
    pname = "System.Xml.XPath";
    version = "4.0.1";
    sha256 = "0fjqgb6y66d72d5n8qq1h213d9nv2vi8mpv8p28j3m9rccmsh04m";
  })
  (fetchNuGet {
    pname = "System.Xml.XPath.XDocument";
    version = "4.0.1";
    sha256 = "1fndc70lbjvh8kxs71c7cidfm8plznd61bg4fwpiyq3mq0qg5z0z";
  })
  (fetchNuGet {
    pname = "Tavis.UriTemplates";
    version = "2.0.0";
    sha256 = "089xzz4pcqx1zf8b0crmh1ac6s4bmdr75m1n63hja5j6kqgxbpa5";
  })
  (fetchNuGet {
    pname = "TestableIO.System.IO.Abstractions";
    version = "19.2.18";
    sha256 = "1hc3cb2d9138bddpflz6mr2dj38ysfllbggfxidq6aijczwixq0p";
  })
  (fetchNuGet {
    pname = "TestableIO.System.IO.Abstractions.Wrappers";
    version = "19.2.18";
    sha256 = "0pl9xjk2jglrhzbvk26b6nrdpzkvp0pwizd5d186w229zhfvmypb";
  })
  (fetchNuGet {
    pname = "Websocket.Client";
    version = "4.5.2";
    sha256 = "1gy2q831byip0p2p3a6zzh3j2p9dl2vz84c5kwl8ksal0h685qvh";
  })
  (fetchNuGet {
    pname = "YamlDotNet";
    version = "13.0.1";
    sha256 = "07shrvmc4ks6l8zsjjgmabyg5j6smqqlh3lvz9111d8wf3gfdcxy";
  })
  (fetchNuGet {
    pname = "YamlDotNet";
    version = "8.1.2";
    sha256 = "1lmi5mdw4067a8yk8gv9kilv1hljflkc45pr5vvz8n09af6gn78b";
  })
]
