# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Update README

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Mondays at 00:00 UTC
    - cron: "0 0 * * 1"

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Update package documentation
        run: nix run nixpkgs#mdsh -- --input README.md --output README.md

      - name: Format code
        run: nix fmt

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update package documentation"
          title: "docs: update package documentation"
          body: |
            This PR updates the package documentation in README.md using the `update-readme.sh` script.

            The documentation is automatically generated from the package metadata.

            Generated by GitHub Actions workflow.
          branch: update-package-docs
          delete-branch: true
          signoff: true
          sign-commits: true
          labels: |
            documentation
            automated
